'use strict';

const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const http = require('node:http');
const mysql = require('mysql2/promise');
const { spawn } = require('node:child_process');

const PORT = 3420;
const BASE = `http://127.0.0.1:${PORT}`;
const DATABASE_URL = process.env.EDUTRACK_DATABASE_URL || 'mysql://edutrack_test:part19_test_password@127.0.0.1:3306/edutrack_part19_test';
const roles = ['DEVELOPER_ROOT','SUPER_ADMIN','NATIONAL_ADMIN','REGIONAL_ADMIN','DISTRICT_ADMIN','HEADTEACHER','TEACHER','PARENT','STUDENT'];
const users = { developer:['dev20@example.invalid','DEVELOPER_ROOT'], super:['super20@example.invalid','SUPER_ADMIN'], national:['national20@example.invalid','NATIONAL_ADMIN'], regional:['regional20@example.invalid','REGIONAL_ADMIN'], regionalB:['regionalb20@example.invalid','REGIONAL_ADMIN'], district:['district20@example.invalid','DISTRICT_ADMIN'], headteacher:['head20@example.invalid','HEADTEACHER'], teacher:['teacher20@example.invalid','TEACHER'], parent:['parent20@example.invalid','PARENT'], student:['student20@example.invalid','STUDENT'] };
const credentials = { password:'Part20-Test-Password!', accessCode:'Part20-Test-Code!' };
function hash(value, salt = crypto.randomBytes(16).toString('hex')) { return `${salt}:${crypto.scryptSync(value, salt, 64).toString('hex')}`; }
function request(pathname, options = {}) { return new Promise((resolve, reject) => { const req=http.request(`${BASE}${pathname}`,{method:options.method||'GET',headers:options.headers||{}},res=>{let raw='';res.on('data',c=>raw+=c);res.on('end',()=>{let body={};try{body=raw?JSON.parse(raw):{}}catch{}resolve({status:res.statusCode,headers:res.headers,body});});});req.on('error',reject);if(options.body)req.write(options.body);req.end();}); }
function cookie(response) { return Array.isArray(response.headers['set-cookie']) ? response.headers['set-cookie'][0].split(';')[0] : ''; }
function waitForServer() { const start=Date.now(); return new Promise((resolve,reject)=>{const poll=()=>request('/api/health').then(r=>r.status===200?resolve():retry()).catch(retry);const retry=()=>Date.now()-start>10000?reject(Error('server readiness timeout')):setTimeout(poll,100);poll();}); }
async function login(dbKey) { const [email,role]=users[dbKey]; const response=await request('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password:credentials.password,accessCode:credentials.accessCode})}); assert.equal(response.status,200,`${role} login failed`); return cookie(response); }
async function main() { const db=await mysql.createConnection(DATABASE_URL); let server;
  try {
    await db.query('SET FOREIGN_KEY_CHECKS=0'); for (const table of ['audit_events','server_sessions','tenant_memberships','user_roles','credentials','users','role_permissions','permissions','schools','districts','regions','tenants','roles','payment_events','subscriptions','payment_transactions','payment_intents','file_records','password_reset_records','schema_migrations']) await db.query(`TRUNCATE TABLE ${table}`).catch(()=>{}); await db.query('SET FOREIGN_KEY_CHECKS=1');
    const migration = require('../db/relational'); await migration.migrate();
    const now = new Date();
    await db.query("INSERT INTO tenants (id,name,tenant_type,active,created_at,updated_at) VALUES ('tenant-a','Tenant A','SCHOOL_GROUP',1,?,?),('tenant-b','Tenant B','SCHOOL_GROUP',1,?,?)",[now,now,now,now]);
    await db.query("INSERT INTO regions (id,name) VALUES ('region-a','Region A'),('region-b','Region B')");
    await db.query("INSERT INTO districts (id,region_id,name) VALUES ('district-a','region-a','District A'),('district-b','region-b','District B')");
    await db.query("INSERT INTO schools (id,tenant_id,district_id,name,active) VALUES ('school-a','tenant-a','district-a','School A',1),('school-b','tenant-b','district-b','School B',1)");
    for (const [key,[email,role]] of Object.entries(users)) { const id=`user-${key}`; await db.query('INSERT INTO users (id,email,staff_id,status,active,development_fixture,hierarchy,scope_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)',[id,email,`STAFF-${key}`,'ACTIVE',1,key==='developer','ALL',JSON.stringify({}),now,now]); await db.query('INSERT INTO credentials (id,user_id,password_hash,access_code_hash,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?)',[`cred-${key}`,id,hash(credentials.password),hash(credentials.accessCode),'ACTIVE',now,now]); await db.query('INSERT INTO user_roles (user_id,role_id) VALUES (?,?)',[id,`role_${role.toLowerCase()}`]); }
    const scoped = { regional:['region-a'], regionalB:['region-b'], district:['district-a'], headteacher:['school-a'], teacher:['school-a'], parent:['school-a'], student:['school-a'] };
    for (const [key,scope] of Object.entries(scoped)) { const tenant=key==='regionalB'?'tenant-b':'tenant-a'; await db.query('INSERT INTO tenant_memberships (user_id,tenant_id,scope_json,active) VALUES (?,?,?,1)',[`user-${key}`,tenant,JSON.stringify({tenantIds:[tenant],regionIds:scope.filter(x=>x.startsWith('region')),districtIds:scope.filter(x=>x.startsWith('district')),schoolIds:scope.filter(x=>x.startsWith('school'))})]); }
    server=spawn(process.execPath,['server.js'],{cwd:require('node:path').resolve(__dirname,'..'),env:{...process.env,EDUTRACK_DATABASE_URL:DATABASE_URL,EDUTRACK_ENABLE_DEV_ACCESS:'true',NODE_ENV:'development',PORT:String(PORT)},stdio:['ignore','pipe','pipe']}); await waitForServer();
    assert.equal((await request('/api/admin/summary')).status,401);
    const superCookie=await login('super'); assert.equal((await request('/api/admin/summary',{headers:{cookie:superCookie}})).status,200);
    const regionalCookie=await login('regional'); const regionalAllowed=await request('/api/admin/authorization-check?permission=scope.read&regionId=region-a',{headers:{cookie:regionalCookie}}); assert.equal(regionalAllowed.status,200); assert.equal((await request('/api/admin/authorization-check?permission=scope.read&regionId=region-b',{headers:{cookie:regionalCookie}})).status,403); assert.equal((await request('/api/admin/authorization-check?permission=scope.read&tenantId=tenant-b',{headers:{cookie:regionalCookie}})).status,403); const regionalBCookie=await login('regionalB'); assert.equal((await request('/api/admin/authorization-check?permission=scope.read&tenantId=tenant-a',{headers:{cookie:regionalBCookie}})).status,403); assert.equal((await request('/api/admin/authorization-check?permission=admin.summary.read&role=SUPER_ADMIN',{headers:{cookie:regionalCookie}})).status,200);
    const districtCookie=await login('district'); assert.equal((await request('/api/admin/authorization-check?permission=scope.read&districtId=district-a',{headers:{cookie:districtCookie}})).status,200); assert.equal((await request('/api/admin/authorization-check?permission=scope.read&districtId=district-b',{headers:{cookie:districtCookie}})).status,403); assert.equal((await request('/api/admin/authorization-check?permission=scope.read&schoolId=school-b',{headers:{cookie:districtCookie}})).status,403);
    const schoolCookie=await login('headteacher'); assert.equal((await request('/api/admin/authorization-check?permission=scope.read&schoolId=school-a',{headers:{cookie:schoolCookie}})).status,200); assert.equal((await request('/api/admin/authorization-check?permission=scope.read&schoolId=school-b',{headers:{cookie:schoolCookie}})).status,403);
    const teacherCookie=await login('teacher'); assert.equal((await request('/api/admin/authorization-check?permission=schools.manage&schoolId=school-a',{headers:{cookie:teacherCookie}})).status,403); assert.equal((await request('/api/admin/authorization-check?permission=admin.summary.read&role=SUPER_ADMIN',{headers:{cookie:teacherCookie}})).status,403);
    const parentCookie=await login('parent'); assert.equal((await request('/api/admin/authorization-check?permission=attendance.manage',{headers:{cookie:parentCookie}})).status,403); const studentCookie=await login('student'); assert.equal((await request('/api/admin/authorization-check?permission=users.manage',{headers:{cookie:studentCookie}})).status,403);
    const devCookie=await login('developer'); assert.equal((await request('/api/admin/authorization-check?permission=roles.manage&tenantId=tenant-b',{headers:{cookie:devCookie}})).status,200);
    await db.query("UPDATE users SET status='SUSPENDED', active=0 WHERE id='user-regional'"); assert.equal((await request('/api/admin/authorization-check?permission=scope.read&regionId=region-a',{headers:{cookie:regionalCookie}})).status,403);
    await db.query("UPDATE users SET status='ACTIVE', active=1 WHERE id='user-regional'"); await db.query("DELETE FROM tenant_memberships WHERE user_id='user-regional'"); assert.equal((await request('/api/admin/authorization-check?permission=scope.read&regionId=region-a',{headers:{cookie:regionalCookie}})).status,403); await db.query("INSERT INTO tenant_memberships (user_id,tenant_id,scope_json,active) VALUES ('user-regional','tenant-a',?,1)",[JSON.stringify({tenantIds:['tenant-a'],regionIds:['region-a']})]); await db.query("DELETE FROM user_roles WHERE user_id='user-regional'"); assert.equal((await request('/api/admin/authorization-check?permission=scope.read&regionId=region-a',{headers:{cookie:regionalCookie}})).status,403);
    const [audit] = await db.query("SELECT event_type FROM audit_events WHERE event_type='FORBIDDEN_API_ACCESS'"); assert.ok(audit.length >= 1);
    console.log('Part 20 RBAC and tenant isolation suite passed.');
  } finally { if(server&&!server.killed)server.kill('SIGTERM'); const migration = require('../db/relational'); await migration.close().catch(()=>{}); await db.query('SET FOREIGN_KEY_CHECKS=0'); for(const table of ['audit_events','server_sessions','tenant_memberships','user_roles','credentials','users','schools','districts','regions','tenants']) await db.query(`TRUNCATE TABLE ${table}`).catch(()=>{}); await db.query('SET FOREIGN_KEY_CHECKS=1'); await db.end(); }
}
main().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
