'use strict';
const assert=require('node:assert/strict');const mysql=require('mysql2/promise');const {spawn,spawnSync}=require('node:child_process');const http=require('node:http');const path=require('node:path');
const ROOT=path.resolve(__dirname,'..');const PORT=3422;const BASE=`http://127.0.0.1:${PORT}`;const DB=process.env.EDUTRACK_DATABASE_URL||'mysql://edutrack_test:part19_test_password@127.0.0.1:3306/edutrack_part19_test';const DEV={email:'part22-academic@example.invalid',password:'Part22-Academic-Password!',accessCode:'Part22-Academic-Code!'};
const env={...process.env,EDUTRACK_DATABASE_URL:DB,DATABASE_URL:'',NODE_ENV:'development',EDUTRACK_ENABLE_DEV_ACCESS:'true',EDUTRACK_DEV_EMAIL:DEV.email,EDUTRACK_DEV_PASSWORD:DEV.password,EDUTRACK_DEV_ACCESS_CODE:DEV.accessCode,PORT:String(PORT)};
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}async function raw(path,opts={}){const r=await fetch(BASE+path,{method:opts.method||'GET',headers:{'Content-Type':'application/json',...(opts.cookie?{Cookie:opts.cookie}:{})},body:opts.body?JSON.stringify(opts.body):undefined});let b={};try{b=await r.json()}catch{}return {status:r.status,body:b,cookie:r.headers.get('set-cookie')||''};}async function wait(){for(let i=0;i<150;i++){try{if((await raw('/api/health')).status===200)return;}catch{}await sleep(100)}throw Error('server readiness timeout');}
async function main(){const db=await mysql.createConnection(DB);let server;try{await db.query('SET FOREIGN_KEY_CHECKS=0');for(const t of ['academic_report_snapshots','mock_scores','mock_components','mock_examinations','promotion_records','result_slips','broadsheets','published_results','scores','examination_components','examinations','examination_types','teacher_attendance_records','student_attendance_records','attendance_registers','teacher_subject_assignments','school_subjects','subjects','academic_configurations','teacher_class_assignments','staff_school_assignments','parent_student_relationships','students','classes','staff','server_sessions','tenant_memberships','user_roles','credentials','users','schools','districts','regions','tenants','payment_events','subscriptions','payment_transactions','payment_intents','file_records','password_reset_records','schema_migrations'])await db.query(`TRUNCATE TABLE ${t}`).catch(()=>{});await db.query('SET FOREIGN_KEY_CHECKS=1');
let m=spawnSync(process.execPath,['scripts/migrate-db.js'],{cwd:ROOT,env,encoding:'utf8'});assert.equal(m.status,0,m.stderr||m.stdout);const now=new Date();await db.query("INSERT INTO tenants (id,name,tenant_type,active,created_at,updated_at) VALUES ('tenant-a','Tenant A','SCHOOL_GROUP',1,?,?)",[now,now]);await db.query("INSERT INTO regions (id,name) VALUES ('region-a','Region A')");await db.query("INSERT INTO districts (id,region_id,name) VALUES ('district-a','region-a','District A')");await db.query("INSERT INTO schools (id,school_code,tenant_id,district_id,name,ownership_type,active,created_at,updated_at) VALUES ('school-a','SCH-A','tenant-a','district-a','School A','PUBLIC',1,?,?)",[now,now,now]);await db.query("INSERT INTO classes (id,name,school_id,tenant_id,status,created_at,updated_at) VALUES ('class-a','Class A','school-a','tenant-a','ACTIVE',?,?)",[now,now,now]);await db.query("INSERT INTO students (id,admission_number,student_identifier,full_name,tenant_id,school_id,class_id,status,created_at,updated_at) VALUES ('student-a','ADM-A','EDU-A','Student A','tenant-a','school-a','class-a','ACTIVE',?,?)",[now,now]);
let p=spawn(process.execPath,['server.js','--provision-dev'],{cwd:ROOT,env,stdio:['ignore','pipe','pipe']});let pout='';p.stdout.on('data',d=>pout+=d);let pe='';p.stderr.on('data',d=>pe+=d);const exit=await new Promise(r=>p.on('exit',(c)=>r(c)));assert.equal(exit,0,pe||pout);server=spawn(process.execPath,['server.js'],{cwd:ROOT,env,stdio:['ignore','pipe','pipe']});await wait();
let noAuth=await raw('/api/domain/subjects');assert.equal(noAuth.status,401);let login=await raw('/api/auth/login',{method:'POST',body:DEV});assert.equal(login.status,200,JSON.stringify(login.body));const cookie=login.cookie.split(';')[0];
async function api(path,method,body){const r=await raw(path,{method,body,cookie});assert.ok(r.status<500,`${method} ${path}: ${r.status} ${JSON.stringify(r.body)}`);return r;}
let cfg=(await api('/api/domain/academic-config','POST',{tenantId:'tenant-a',schoolId:'school-a',academicYear:'2026/2027',term:'First Term',week:1,openingDate:'2026-09-01',closingDate:'2026-12-20'})).body.configuration;assert.ok(cfg.id);assert.equal((await api('/api/domain/academic-config?schoolId=school-a')).body.configurations.length,1);await api('/api/domain/academic-config/'+cfg.id,'PATCH',{week:2});
let subj=(await api('/api/domain/subjects','POST',{tenantId:'tenant-a',schoolId:'school-a',code:'MATH',name:'Mathematics'})).body.subject;assert.equal((await api('/api/domain/subjects?schoolId=school-a')).body.subjects[0].code,'MATH');await api('/api/domain/subjects/'+subj.id,'PATCH',{name:'Mathematics Updated'});
let typ=(await api('/api/domain/examination-types','POST',{tenantId:'tenant-a',schoolId:'school-a',name:'End of Term',category:'NORMAL'})).body.examinationType;let exam=(await api('/api/domain/examinations','POST',{tenantId:'tenant-a',schoolId:'school-a',classId:'class-a',academicConfigId:cfg.id,examinationTypeId:typ.id,name:'Term Examination',components:[{subjectId:subj.id,name:'Paper 1',maximumScore:100}]})).body.examination;assert.ok(exam.id);const comps=await db.query('SELECT id FROM examination_components WHERE examination_id=?',[exam.id]);const componentId=comps[0][0].id;
let att=(await api('/api/domain/attendance','POST',{tenantId:'tenant-a',schoolId:'school-a',classId:'class-a',attendanceDate:'2026-09-01',records:[{studentId:'student-a',status:'PRESENT'}]})).body.attendance;assert.ok(att.id);let attRows=await db.query('SELECT id FROM student_attendance_records WHERE register_id=?',[att.id]);await api('/api/domain/attendance/'+attRows[0][0].id,'PATCH',{status:'ABSENT',note:'Corrected'});
let scoreResponse=await api('/api/domain/scores','POST',{tenantId:'tenant-a',schoolId:'school-a',classId:'class-a',studentId:'student-a',subjectId:subj.id,examinationId:exam.id,componentId,rawScore:'84',maximumScore:'100'});assert.equal(scoreResponse.status,201,JSON.stringify(scoreResponse.body));let score=scoreResponse.body.score;assert.ok(score,JSON.stringify(scoreResponse.body));assert.equal(Number(score.rawScore),84);let bad=await raw('/api/domain/scores',{method:'POST',body:{tenantId:'tenant-a',schoolId:'school-a',classId:'class-a',studentId:'student-a',subjectId:subj.id,examinationId:exam.id,componentId,rawScore:'101',maximumScore:'100'},cookie});assert.equal(bad.status,400);let dup=await raw('/api/domain/scores',{method:'POST',body:{tenantId:'tenant-a',schoolId:'school-a',classId:'class-a',studentId:'student-a',subjectId:subj.id,examinationId:exam.id,componentId,rawScore:'85',maximumScore:'100'},cookie});assert.equal(dup.status,409);await api('/api/domain/scores/'+score.id,'PATCH',{rawScore:86});
let result=(await api('/api/domain/results/calculate','POST',{tenantId:'tenant-a',schoolId:'school-a',classId:'class-a',studentId:'student-a',academicConfigId:cfg.id,examinationId:exam.id})).body.result;assert.equal((typeof (result.resultJson||result.result_json)==='string'?JSON.parse(result.resultJson||result.result_json):(result.resultJson||result.result_json)).percentage,86);let published=(await api('/api/domain/results/publish','POST',{resultId:result.id})).body.result;assert.equal(published.publicationStatus,'PUBLISHED');assert.equal((await api('/api/domain/result-slips/'+result.id)).body.resultSlip.id,result.id);
let promotion=(await api('/api/domain/promotions','POST',{tenantId:'tenant-a',schoolId:'school-a',studentId:'student-a',sourceClassId:'class-a',destinationClassId:'class-a',academicConfigId:cfg.id,decision:'PROMOTE'}));assert.equal(promotion.status,400);
let mock=(await api('/api/domain/mock-examinations','POST',{tenantId:'tenant-a',schoolId:'school-a',classId:'class-a',academicConfigId:cfg.id,label:'1st MOCK',formatCode:'B'})).body.mockExamination;assert.ok(mock.id);let report=(await api('/api/domain/academic-reports/attendance')).body.reports;assert.equal(Array.isArray(report),true);let audits=await db.query("SELECT event_type FROM audit_events WHERE event_type IN ('ACADEMIC_CONFIG_CREATED','SUBJECT_CREATED','ATTENDANCE_CREATED','EXAMINATION_CREATED','SCORE_CREATED','RESULT_CALCULATED','RESULT_PUBLISHED','MOCK_EXAM_CREATED')");assert.ok(audits[0].length>=8);console.log('Part 22 academic operations persistence suite passed.');
}finally{if(server&&!server.killed)server.kill('SIGTERM');await db.query('SET FOREIGN_KEY_CHECKS=0').catch(()=>{});for(const t of ['academic_report_snapshots','mock_scores','mock_components','mock_examinations','promotion_records','result_slips','broadsheets','published_results','scores','examination_components','examinations','examination_types','teacher_attendance_records','student_attendance_records','attendance_registers','teacher_subject_assignments','school_subjects','subjects','academic_configurations','teacher_class_assignments','staff_school_assignments','parent_student_relationships','students','classes','staff','server_sessions','tenant_memberships','user_roles','credentials','users','schools','districts','regions','tenants','payment_events','subscriptions','payment_transactions','payment_intents','file_records','password_reset_records','schema_migrations'])await db.query(`TRUNCATE TABLE ${t}`).catch(()=>{});await db.query('SET FOREIGN_KEY_CHECKS=1').catch(()=>{});await db.end();}}
main().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
