'use strict';
const assert=require('node:assert/strict');const {spawn}=require('node:child_process');const path=require('node:path');
const ROOT=path.resolve(__dirname,'..');const DB=process.env.EDUTRACK_DATABASE_URL||'mysql://edutrack_test:part19_test_password@127.0.0.1:3306/edutrack_part19_test';
const base={NODE_ENV:'production',EDUTRACK_DATABASE_URL:DB,EDUTRACK_ENABLE_DEV_ACCESS:'false',EDUTRACK_ALLOWED_ORIGINS:'https://app.example.com',PAYSTACK_SECRET_KEY:'part34-test-only',PAYSTACK_WEBHOOK_SECRET:'part34-test-only',EDUTRACK_PAYMENT_PLANS:JSON.stringify({basic:{amount:1000,currency:'GHS',durationDays:30}}),EDUTRACK_STORAGE_MODE:'s3',EDUTRACK_STORAGE_BUCKET:'part34-test-private',AWS_ACCESS_KEY_ID:'part34-test-only',AWS_SECRET_ACCESS_KEY:'part34-test-only'};
function runPreflight(extra={}){return new Promise(resolve=>{const child=spawn(process.execPath,['scripts/production-preflight.js'],{cwd:ROOT,env:{...process.env,...extra}});let out='';child.stdout.on('data',d=>out+=d);child.stderr.on('data',d=>out+=d);child.on('close',code=>resolve({code,out}));})}
async function waitHealth(port,child){for(let i=0;i<40;i++){try{const r=await fetch(`http://127.0.0.1:${port}/api/health`);return r}catch{}await new Promise(r=>setTimeout(r,150));}child.kill('SIGTERM');throw new Error('production health endpoint did not start')}
(async()=>{
 let result=await runPreflight({NODE_ENV:'production'});assert.notEqual(result.code,0);assert.match(result.out,/missing required variables/);assert.doesNotMatch(result.out,/part34-test-only|part19_test_password/);
 result=await runPreflight({...base});assert.equal(result.code,0);assert.match(result.out,/"ok": true/);assert.doesNotMatch(result.out,/part34-test-only|part19_test_password/);
 result=await runPreflight({...base,EDUTRACK_ALLOWED_ORIGINS:'*'});assert.notEqual(result.code,0);assert.match(result.out,/wildcards/);
 result=await runPreflight({...base,EDUTRACK_STORAGE_MODE:'local'});assert.notEqual(result.code,0);assert.match(result.out,/must be s3/);
 const port=3424;const child=spawn(process.execPath,['server.js'],{cwd:ROOT,env:{...process.env,...base,PORT:String(port)}});let startup='';child.stderr.on('data',d=>startup+=d);child.stdout.on('data',d=>startup+=d);try{const response=await waitHealth(port,child);assert.equal(response.status,200);const health=await response.json();assert.deepEqual(health,{ok:true,persistence:'relational'});const headers=Object.fromEntries(response.headers);assert.equal(headers['strict-transport-security'],'max-age=31536000; includeSubDomains');assert.doesNotMatch(JSON.stringify(health),/secret|password|token|path|mysql|paystack/i);const originResponse=await fetch(`http://127.0.0.1:${port}/api/health`,{headers:{Origin:'https://evil.example'}});assert.equal(originResponse.status,403);}finally{child.kill('SIGTERM');await new Promise(resolve=>child.once('close',resolve));}
 console.log('Part 34 production deployment validation suite passed.');
})().catch(error=>{console.error(error.stack||error);process.exit(1)});
