'use strict';
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const http=require('node:http');
const mysql=require('mysql2/promise');
const {spawn}=require('node:child_process');
const path=require('node:path');
const ROOT=path.resolve(__dirname,'..');
const PORT=3421; const BASE=`http://127.0.0.1:${PORT}`;
const URL_DB=process.env.EDUTRACK_DATABASE_URL||'mysql://edutrack_test:part19_test_password@127.0.0.1:3306/edutrack_part19_test';
const PASSWORD='Part21-Test-Password!'; const CODE='Part21-Test-Code!';
function h(value){const salt=crypto.randomBytes(16).toString('hex');return `${salt}:${crypto.scryptSync(value,salt,64).toString('hex')}`;}
function request(pathname,opts={}){return new Promise((resolve,reject)=>{const req=http.request(`${BASE}${pathname}`,{method:opts.method||'GET',headers:opts.headers||{}},res=>{let raw='';res.on('data',c=>raw+=c);res.on('end',()=>{let body={};try{body=raw?JSON.parse(raw):{}}catch{}resolve({status:res.statusCode,headers:res.headers,body});});});req.on('error',reject);if(opts.body)req.write(opts.body);req.end();});}
function cookie(r){return Array.isArray(r.headers['set-cookie'])?r.headers['set-cookie'][0].split(';')[0]:'';}
function jsonBody(value){return {headers:{'content-type':'application/json',origin:BASE},body:JSON.stringify(value)};}
function wait(){const started=Date.now();return new Promise((resolve,reject)=>{const poll=()=>request('/api/health').then(r=>r.status===200?resolve():retry()).catch(retry);const retry=()=>Date.now()-started>10000?reject(Error('server readiness timeout')):setTimeout(poll,100);poll();});}
async function main(){const db=await mysql.createConnection(URL_DB);let server;let relational;
try{
 await db.query('SET FOREIGN_KEY_CHECKS=0');for(const table of ['audit_events','teacher_class_assignments','staff_school_assignments','parent_student_relationships','students','classes','staff','server_sessions','tenant_memberships','user_roles','credentials','users','schools','districts','regions','tenants','role_permissions','permissions','roles','payment_events','subscriptions','payment_transactions','payment_intents','file_records','password_reset_records','schema_migrations'])await db.query(`TRUNCATE TABLE ${table}`).catch(()=>{});await db.query('SET FOREIGN_KEY_CHECKS=1');
 relational=require('../db/relational'); await relational.migrate(); await relational.migrate();
 const [migrations]=await db.query('SELECT version FROM schema_migrations');assert.ok(migrations.some(r=>Number(r.version)===8));
 const now=new Date(); await db.query("INSERT INTO tenants (id,name,tenant_type,active,created_at,updated_at) VALUES ('tenant-a','Tenant A','SCHOOL_GROUP',1,?,?),('tenant-b','Tenant B','SCHOOL_GROUP',1,?,?)",[now,now,now,now]);
 await db.query("INSERT INTO regions (id,name) VALUES ('region-a','Region A'),('region-b','Region B')"); await db.query("INSERT INTO districts (id,region_id,name) VALUES ('district-a','region-a','District A'),('district-b','region-b','District B')");
 await db.query("INSERT INTO users (id,email,staff_id,status,active,development_fixture,hierarchy,scope_json,created_at,updated_at) VALUES ('super21','super21@example.invalid','SUPER21','ACTIVE',1,0,'ROOT',JSON_OBJECT(),?,?)",[now,now]); await db.query("INSERT INTO credentials (id,user_id,password_hash,access_code_hash,status,created_at,updated_at) VALUES ('cred-super21','super21',? ,?,'ACTIVE',?,?)",[h(PASSWORD),h(CODE),now,now]); await db.query("INSERT INTO user_roles (user_id,role_id) VALUES ('super21','role_super_admin')");
 await db.query("INSERT INTO users (id,email,staff_id,status,active,development_fixture,hierarchy,scope_json,created_at,updated_at) VALUES ('regional21','regional21@example.invalid','REG21','ACTIVE',1,0,'REGION',JSON_OBJECT(),?,?)",[now,now]); await db.query("INSERT INTO credentials (id,user_id,password_hash,access_code_hash,status,created_at,updated_at) VALUES ('cred-regional21','regional21',? ,?,'ACTIVE',?,?)",[h(PASSWORD),h(CODE),now,now]); await db.query("INSERT INTO user_roles (user_id,role_id) VALUES ('regional21','role_regional_admin')"); await db.query("INSERT INTO tenant_memberships (user_id,tenant_id,scope_json,active) VALUES ('regional21','tenant-a',?,1)",[JSON.stringify({tenantIds:['tenant-a'],regionIds:['region-a']})]);
 server=spawn(process.execPath,['server.js'],{cwd:ROOT,env:{...process.env,EDUTRACK_DATABASE_URL:URL_DB,NODE_ENV:'development',PORT:String(PORT)},stdio:['ignore','pipe','pipe']});await wait();
 const login=await request('/api/auth/login',{method:'POST',...jsonBody({email:'super21@example.invalid',password:PASSWORD,accessCode:CODE})});assert.equal(login.status,200);const superCookie=cookie(login);
 assert.equal((await request('/api/domain/regions',{headers:{cookie:superCookie}})).status,200);assert.equal((await request('/api/domain/districts?regionId=region-a',{headers:{cookie:superCookie}})).status,200);
 const schoolPayload={schoolCode:'SCH-21-A',name:'School A',ownershipType:'PUBLIC',tenantId:'tenant-a',regionId:'region-a',districtId:'district-a',address:'A Road',contactPhone:'+233000000001',contactEmail:'a@example.invalid'};
 const createdSchool=await request('/api/domain/schools',{method:'POST',...jsonBody(schoolPayload),headers:{...jsonBody(schoolPayload).headers,cookie:superCookie}});assert.equal(createdSchool.status,201);const schoolId=createdSchool.body.school.id;assert.match(schoolId,/^school_/);assert.equal(createdSchool.body.school.schoolCode,'SCH-21-A');assert.equal((await request('/api/domain/schools',{headers:{cookie:superCookie}})).body.schools.length,1);
 assert.equal((await request('/api/domain/schools',{method:'POST',...jsonBody(schoolPayload),headers:{...jsonBody(schoolPayload).headers,cookie:superCookie}})).status,409);
 assert.equal((await request('/api/domain/schools',{method:'POST',...jsonBody({...schoolPayload,schoolCode:'SCH-21-B',districtId:'district-b'}),headers:{...jsonBody(schoolPayload).headers,cookie:superCookie}})).status,400);
 const updated=await request(`/api/domain/schools/${schoolId}`,{method:'PATCH',...jsonBody({name:'School A Updated'}),headers:{...jsonBody({}).headers,cookie:superCookie}});assert.equal(updated.status,200);assert.equal(updated.body.school.name,'School A Updated');
 const createdSchoolB=await request('/api/domain/schools',{method:'POST',...jsonBody({...schoolPayload,schoolCode:'SCH-21-B',name:'School B',tenantId:'tenant-b',regionId:'region-b',districtId:'district-b'}),headers:{...jsonBody({}).headers,cookie:superCookie}});assert.equal(createdSchoolB.status,201);const schoolB=createdSchoolB.body.school.id;
 const teacherId='teacher-user-21';await db.query("INSERT INTO users (id,email,staff_id,status,active,development_fixture,hierarchy,scope_json,created_at,updated_at) VALUES (?,?,'TEACH21','ACTIVE',1,0,'SCHOOL',JSON_OBJECT(),?,?)",[teacherId,'teacher21@example.invalid',now,now]);await db.query("INSERT INTO credentials (id,user_id,password_hash,access_code_hash,status,created_at,updated_at) VALUES (?, ?, ?, ?,'ACTIVE',?,?)",['cred-teacher21',teacherId,h(PASSWORD),h(CODE),now,now]);
 const staffPayload={staffIdentifier:'STAFF-21-A',fullName:'Teacher A',email:'teacher21@example.invalid',tenantId:'tenant-a',schoolId,role:'TEACHER',userId:teacherId};const staff=await request('/api/domain/staff',{method:'POST',...jsonBody(staffPayload),headers:{...jsonBody({}).headers,cookie:superCookie}});assert.equal(staff.status,201);const staffId=staff.body.staff.id;assert.equal(staff.body.staff.userId,teacherId);assert.equal((await request('/api/domain/staff',{headers:{cookie:superCookie}})).body.staff.length,1);
 assert.equal((await request('/api/domain/staff',{method:'POST',...jsonBody(staffPayload),headers:{...jsonBody({}).headers,cookie:superCookie}})).status,409); assert.equal((await request('/api/domain/staff',{method:'POST',...jsonBody({...staffPayload,staffIdentifier:'STAFF-21-B',role:'DEVELOPER_ROOT'}),headers:{...jsonBody({}).headers,cookie:superCookie}})).status,400);
 const classA=await request('/api/domain/classes',{method:'POST',...jsonBody({name:'Class A',schoolId,tenantId:'tenant-a'}),headers:{...jsonBody({}).headers,cookie:superCookie}});assert.equal(classA.status,201);const classId=classA.body.class.id;const classB=await request('/api/domain/classes',{method:'POST',...jsonBody({name:'Class B',schoolId:schoolB,tenantId:'tenant-b'}),headers:{...jsonBody({}).headers,cookie:superCookie}});assert.equal(classB.status,201);
 assert.equal((await request('/api/domain/teacher-class-assignments',{method:'POST',...jsonBody({staffId,classId}),headers:{...jsonBody({}).headers,cookie:superCookie}})).status,200);assert.equal((await request('/api/domain/teacher-class-assignments',{method:'POST',...jsonBody({staffId,classId:classB.body.class.id}),headers:{...jsonBody({}).headers,cookie:superCookie}})).status,400);
 const parentId='parent-user-21';await db.query("INSERT INTO users (id,email,status,active,development_fixture,created_at,updated_at) VALUES (?,?,'ACTIVE',1,0,?,?)",[parentId,'parent21@example.invalid',now,now]);await db.query("INSERT INTO user_roles (user_id,role_id) VALUES (?, 'role_parent')",[parentId]);await db.query("INSERT INTO tenant_memberships (user_id,tenant_id,scope_json,active) VALUES (?, 'tenant-a', ?, 1)",[parentId,JSON.stringify({tenantIds:['tenant-a'],schoolIds:[schoolId]})]);
 const studentPayload={admissionNumber:'ADM-21-A',fullName:'Student A',tenantId:'tenant-a',schoolId,parentUserId:parentId};const student=await request('/api/domain/students',{method:'POST',...jsonBody(studentPayload),headers:{...jsonBody({}).headers,cookie:superCookie}});assert.equal(student.status,201);const studentId=student.body.student.id;assert.match(student.body.student.studentIdentifier,/^EDU-/);assert.equal((await request('/api/domain/students',{method:'POST',...jsonBody(studentPayload),headers:{...jsonBody({}).headers,cookie:superCookie}})).status,409);assert.equal((await request(`/api/domain/students/${studentId}`,{method:'PATCH',...jsonBody({gender:'F'}),headers:{...jsonBody({}).headers,cookie:superCookie}})).status,200);
 assert.equal((await request('/api/domain/parent-student-relationships',{method:'POST',...jsonBody({parentUserId:parentId,studentId}),headers:{...jsonBody({}).headers,cookie:superCookie}})).status,409);
 const regionalLogin=await request('/api/auth/login',{method:'POST',...jsonBody({email:'regional21@example.invalid',password:PASSWORD,accessCode:CODE})});assert.equal(regionalLogin.status,200,JSON.stringify(regionalLogin.body));const regionalCookie=cookie(regionalLogin);const regionalSchools=await request('/api/domain/schools?tenantId=tenant-b',{headers:{cookie:regionalCookie}});assert.equal(regionalSchools.status,403,JSON.stringify(regionalSchools.body));assert.equal((await request('/api/domain/students',{method:'POST',...jsonBody({admissionNumber:'ADM-21-B',fullName:'Student B',tenantId:'tenant-b',schoolId:schoolB}),headers:{...jsonBody({}).headers,cookie:regionalCookie}})).status,403);
 const [audit]=await db.query("SELECT event_type FROM audit_events WHERE event_type IN ('SCHOOL_CREATED','STAFF_CREATED','STUDENT_CREATED','CLASS_CREATED','TEACHER_CLASS_ASSIGNED')");assert.ok(audit.length>=4);
 console.log('Part 21 core domain persistence suite passed.');
}finally{if(server&&!server.killed)server.kill('SIGTERM');if(relational)await relational.close().catch(()=>{});await db.query('SET FOREIGN_KEY_CHECKS=0');for(const table of ['audit_events','teacher_class_assignments','staff_school_assignments','parent_student_relationships','students','classes','staff','server_sessions','tenant_memberships','user_roles','credentials','users','schools','districts','regions','tenants'])await db.query(`TRUNCATE TABLE ${table}`).catch(()=>{});await db.query('SET FOREIGN_KEY_CHECKS=1');await db.end();}}
main().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
