'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const guide=fs.readFileSync(path.join(root,'school-user-guide.js'),'utf8');
const sidebar=fs.readFileSync(path.join(root,'school-sidebar.js'),'utf8');
for(const label of ['Online Admission','Communication Hub','Chat','Control Panel','Analytics Narrative','Quiz','Admissions Review','Transport Management','Hostel Management','QR Attendance'])assert.ok(guide.includes(`title:'${label}'`),'missing Part 7 guide entry: '+label);
assert.match(guide,/does not create a permanent Student ID or Index Number/i);
assert.match(guide,/push notifications remain unavailable until device infrastructure is configured/i);
assert.match(guide,/relationship-scoped School chat/i);
assert.match(guide,/must not treat it as a District, Regional or National control function/i);
assert.match(guide,/does not provide School-level quiz creation or assignment controls/i);
assert.match(guide,/Start Review where available → Approve, Request Correction or Reject/i);
assert.match(guide,/create a duplicate permanent identity/i);
assert.match(guide,/offline movement events are queued for synchronization/i);
assert.match(guide,/offline roll calls queue for synchronization/i);
assert.match(guide,/Start camera or use the authorized token/i);
for(const label of ['Communication Hub','Chat','Control Panel','Analytics Narrative','Quiz','Transport Management','Hostel Management','QR Attendance'])assert.match(sidebar,new RegExp(`['\"]${label}['\"]`),'missing integrated navigation: '+label);
console.log('School user guide Part 7 integrated-school-module coverage passed.');
