'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const guide=fs.readFileSync(path.join(root,'school-user-guide.js'),'utf8');
const sidebar=fs.readFileSync(path.join(root,'school-sidebar.js'),'utf8');
const loader=fs.readFileSync(path.join(root,'school-module-loader.js'),'utf8');
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const required=['Dashboard','Switch Language','Setup / Config','Subject Config','Reports','Fee Hub','Teachers Register','Integrity Check','Cloud Sync','User Accounts & Access Control','Assign Class to Teachers','Reassign Class','Assign Roles','Publish Results','Block Result','Publish Mock Results','Block Mock Result','Student Admission & Transfer Management','New Student Admission','Transfer Admission','Student Search / Profile','Staff Registry','Score Entry','Multi-Subject Entry','Mock Entry','Pupils Register','SHEP Activities','Subject Register','Sporting Activities','Learning Management (LMS)','Student Database','Result Slip','Mock Result','Mock Exam Analysis','Broadsheet','Rankings','Chart Analysis','Index Generator','AI Analytics Engine','Workflow Automation','Business Intelligence','Student Health','Library','Timetable AI','Procurement','Guidance & Counselling','Online Admission','Communication Hub','Chat','Control Panel','Analytics Narrative','Quiz','Admissions Review','Transport Management','Hostel Management','QR Attendance','User Guide','Copyright','Acknowledgement','Developer','Log Out'];
for(const label of required)assert.ok(sidebar.includes("'"+label+"'")||guide.includes(label),'missing final School guide/sidebar alignment: '+label);
assert.match(sidebar,/Student Admission & Transfer Management/);
assert.doesNotMatch(sidebar,/GNSIS \/ Admissions/);
assert.match(guide,/keywords:'[^']*GNSIS[^']*'/);
assert.match(loader,/school-user-guide\.js/);
assert.match(server,/school-user-guide\.js/);
assert.equal((sidebar.match(/group\('school-smart-management'/g)||[]).length,1,'exactly one consolidated Smart group is required');
assert.match(sidebar,/EDUTRACK_STAFF_MANAGEMENT_PART3&&EDUTRACK_STAFF_MANAGEMENT_PART3\.open/,'User Management must retain its real implementation');
assert.match(sidebar,/sld\('Sporting Activities','⚽','sporting'\)/,'Sporting Activities must retain its real School-level implementation');
assert.doesNotMatch(sidebar,/Coming Soon/i);
assert.match(sidebar,/ent-nav-section','ng-enterprise','ent-p2-nav-section','ng-enterprise-p2/,'legacy Enterprise navigation must be hidden at School level');
assert.match(guide,/function visible\(label\)/,'guide eligibility must remain visibility/RBAC-aware');
assert.match(guide,/Android iPhone tablet/i);
assert.match(guide,/nothing appears after Log Out/i);
assert.doesNotMatch(guide,/District, Regional, or National officer guidance/i);
console.log('Final School User Guide/sidebar integrated alignment contract passed.');
