'use strict';
const assert = require('node:assert/strict');
const { category } = require('../lib/tidb-connectivity-diagnostic');
assert.equal(category({ code: 'ENOTFOUND' }), 'ENDPOINT');
assert.equal(category({ code: 'ECONNREFUSED' }), 'NETWORK');
assert.equal(category({ code: 'ETIMEDOUT' }), 'NETWORK');
assert.equal(category({ code: 'ER_ACCESS_DENIED_ERROR' }), 'AUTHENTICATION');
assert.equal(category({ code: 'ER_BAD_DB_ERROR' }), 'DATABASE');
assert.equal(category({ code: 'HANDSHAKE_SSL_ERROR' }), 'TLS');
assert.equal(category({ code: 'unrecognized' }), 'UNKNOWN');
console.log('TiDB connectivity diagnostic sanitization passed.');
