(function(){'use strict';if(window.__EDUTRACK_SCHOOL_SIDEBAR__)return;window.__EDUTRACK_SCHOOL_SIDEBAR__=true;
function get(k){try{return String(localStorage.getItem(k)||'').toUpperCase()}catch(e){return''}}function esc(v){return String(v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function item(label,icon,action,attrs){return'<button type="button" class="nav-item school-nav-item" data-school-nav="'+esc(label)+'" '+(attrs||'')+' onclick="'+action+'"><span class="icon">'+icon+'</span><span class="nav-label">'+esc(label)+'</span></button>'}
function page(label,icon,id,after){return item(label,icon,"showPage('"+id+"',this)"+(after?';'+after:''))}function sld(label,icon,section){return item(label,icon,"window.EMS_SLD&&EMS_SLD.openSection('"+section+"')")}
function api(label,icon,name){return item(label,icon,"window."+name+"&&typeof window."+name+".open==='function'&&window."+name+".open()")}
function group(id,label,icon,children,attrs){return'<div class="nav-group school-nav-group" id="'+id+'" '+(attrs||'')+'><button type="button" class="nav-group-header" onclick="EDUTRACK_SCHOOL_SIDEBAR.toggle(\''+id+'\')" aria-controls="'+id+'-items" aria-expanded="false"><span class="icon">'+icon+'</span><span class="nav-label">'+esc(label)+'</span><span class="nav-group-arrow">▶</span></button><div class="nav-group-items" id="'+id+'-items">'+children.join('')+'</div></div>'}
function result(label,icon,id,renderer,arg){return page(label,icon,id,"setTimeout(function(){window."+renderer+"&&"+renderer+".render("+(arg||'')+");},20)")}
function build(){var root=document.getElementById('sg-school-level'),wrap=root&&root.querySelector(':scope > .nav-supergroup-items');if(!wrap||root.dataset.schoolSidebarReady==='true')return false;
var reports=group('school-reports','Reports','📑',[page('School Report Generator','📘','schoolreport','window.SRG&&SRG.render()'),page('Academic Year Report','📚','annualreport','window.SRG_ANNUAL&&SRG_ANNUAL.render()')]);
var fees=group('school-fee-hub','Fee Hub','🏦',[item('FMS Dashboard','📊',"fmsShowPage('fms-dashboard',this)"),item('Fee Setup','🏷️',"fmsShowPage('fms-fee-types',this)"),item('Class Structures','📐',"fmsShowPage('fms-fee-structure',this)"),item('Record Payment','💳',"fmsShowPage('fms-record-payment',this)"),item('Receipt Registry','🧾',"fmsShowPage('fms-receipts',this)"),item('Outstanding Fees','⚠️',"fmsShowPage('fms-outstanding',this)"),item('Financial Reports','📈',"fmsShowPage('fms-reports-hub',this)")],'data-private-school-feature="true"');
var teacherRegister=group('school-teachers-register','Teachers Register','👨‍🏫',[page('Attendance Register','📋','teachers'),page('Teacher Setup','👥','teachersetup'),page('Term Config','📅','termconfig'),page('Attendance Report','📊','tattendreport'),page('Analytics Dashboard','📈','tattendanalytics'),page('Notifications Log','🔔','tattendnotif'),page('Teacher Alert (5-Day / SISO)','🆘','teachalert5'),page('Teacher Critical Alert (1-Month / HR)','🚨','teachalertmonth')]);
var ht=[page('Subject Config','📚','subjects'),reports,fees,teacherRegister,group('school-system-tools','System Tools','🔧',[page('Integrity Check','🔒','integrity'),page('Cloud Sync','☁️','sync')]),sld('User Management','👤','access-control'),result('Assign Class to Teachers','🧑‍💼','ges-assign-class','GES_TEACHER_ASSIGN_UI',"'assign'"),result('Reassign Class','🔁','ges-assign-class','GES_TEACHER_ASSIGN_UI',"'reassign'"),result('Assign Roles','🧑‍💼','ges-assign-roles','GES_ROLE_ASSIGN_UI'),result('Publish Results','🔐','ges-publish-results','GES_RESULT_PUBLISH_UI'),result('Block Result','⛔','ges-block-result','GES_RESULT_BLOCK_UI'),result('Publish Mock Results','🎯','ges-publish-mock-results','GES_MOCK_RESULT_PUBLISH_UI'),result('Block Mock Result','🚫','ges-block-mock-result','GES_MOCK_RESULT_BLOCK_UI'),group('school-gnsis','GNSIS / Admissions','🪪',[page('New Student Admission','➕','gnsis-admission'),item('Transfer Admission','🔁',"window.EMS_GNSIS_LIFE&&EMS_GNSIS_LIFE.open('gnsis-transfer')"),item('Student Search / Profile','🔎',"window.EMS_GNSIS_LIFE&&EMS_GNSIS_LIFE.open('gnsis-search')")]),item('Staff Management','👥',"document.getElementById('p3-staff-management-nav')&&document.getElementById('p3-staff-management-nav').click()")];
var pupils=group('school-pupils-register','Pupils Register','👧',[page('Attendance Register','📋','pupils'),page('Pupil Setup','📋','pupilsetup'),page('SMS Logs','📨','smslogs'),page('Pupils Report','📊','pupilreport'),page('Audit Trail','🔍','pa-audittrail'),page('Attendance Reports','📈','pa-reporting'),page('Automation Hub','⚡','pa-automation'),page('Headteacher Critical Alert (3-Day)','🚨','htcritical')]);
var tc=[page('Score Entry','📝','entry'),page('Multi-Subject Entry','📚','multientry'),page('Mock Entry','📋','mock'),pupils,sld('SHEP Activities','🩺','shep'),sld('Subject Register','📖','subject-register'),sld('Sporting Activities','⚽','sporting'),result('Publish Results','🔐','ges-publish-results','GES_RESULT_PUBLISH_UI'),result('Block Result','⛔','ges-block-result','GES_RESULT_BLOCK_UI'),result('Publish Mock Results','🎯','ges-publish-mock-results','GES_MOCK_RESULT_PUBLISH_UI'),result('Block Mock Result','🚫','ges-block-mock-result','GES_MOCK_RESULT_BLOCK_UI'),page('Learning Management (LMS)','🎓','lms-teacher')];
var shared=[page('Student Database','🧑‍🎓','students'),page('Result Slip','📄','slip'),page('Mock Result','🧪','mockresult'),page('Mock Exam Analysis','🎯','mockanalysis'),page('Broadsheet','📊','broadsheet'),page('Rankings','🏆','rankings'),page('Chart Analysis','📈','analytics'),page('Index Generator','🔢','indexgen')];
var smart=[page('AI Analytics Engine','🤖','ent-ai'),page('Workflow Automation','🔁','ent-workflow'),page('Business Intelligence','📊','ent-bi'),page('Student Health','🏥','ent-health'),page('Library','📚','ent-library'),page('Timetable AI','🗓️','ent-timetable'),page('Procurement','🧾','ent-procurement'),page('Guidance & Counselling','🧑‍🎓','ent-guidance')];
var integrated=[api('Online Admission','📝','EDUTRACK_ONLINE_ADMISSIONS'),api('Communication Hub','💬','EDUTRACK_COMMUNICATION_HUB'),api('Chat','💬','EDUTRACK_CHAT'),api('Control Panel','📊','EDUTRACK_CONTROL_PANEL'),page('Analytics Narrative','🧠','ges-school',"setTimeout(function(){window.EDUTRACK_ANALYTICS_NARRATIVE&&EDUTRACK_ANALYTICS_NARRATIVE.generate('page-ges-school');},50)"),api('Quiz','📝','EDUTRACK_QUIZ_MODULE'),api('Admissions Review','✅','EDUTRACK_ADMISSIONS_REVIEW'),page('Transport Management','🚌','transport-management'),page('Hostel Management','🏠','hostel-management'),page('QR Attendance','▣','qr-attendance')];
wrap.innerHTML='<div class="nav-section school-nav-section"><span class="nav-section-label">Overview</span></div>'+page('Dashboard','📊','dashboard')+item('Switch Language','🌐','window.EMS_I18N&&EMS_I18N.openSwitcher()')+page('Setup / Config','⚙️','setup')+group('ng-cat-headteacher','Headteacher','🧑‍💼',ht,'data-role-category="Headteacher"')+group('ng-cat-teachers','Teachers','👩‍🏫',tc,'data-role-category="Teachers"')+group('ng-cat-shared','Shared','🔗',shared,'data-role-category="Shared"')+group('school-smart-management','Smart School Management & Intelligence','🧠',smart)+group('school-integrated-modules','Integrated School Modules','🔌',integrated)+'<div id="school-headteacher-anchor" hidden></div><div id="school-teachers-anchor" hidden></div><div id="school-shared-anchor" hidden></div>';root.dataset.schoolSidebarReady='true';policy(root);return true}
function policy(root){var r=get('v43_login_role'),ht=document.getElementById('ng-cat-headteacher'),admin=/HEADTEACHER|ASSISTANT HEAD|PROPRIETOR|PROPRIETRESS|ADMIN/.test(r);if(ht)ht.hidden=!admin;var cfg=window.CONFIG||{},type=String(cfg.schoolType||cfg.ownershipType||cfg.ownership||'').toUpperCase(),government=/PUBLIC|GOVERNMENT/.test(type);root.querySelectorAll('[data-private-school-feature="true"]').forEach(function(n){n.hidden=government})}
function hide(n){if(!n)return;n.hidden=true;n.style.setProperty('display','none','important')}
function clean(){var root=document.getElementById('sg-school-level');if(!root||root.dataset.schoolSidebarReady!=='true')return;var wrap=root.querySelector(':scope > .nav-supergroup-items');if(wrap)Array.prototype.forEach.call(wrap.children,function(n){if(!n.classList.contains('school-nav-item')&&!n.classList.contains('school-nav-group')&&!n.classList.contains('school-nav-section')&&!/^school-(headteacher|teachers|shared)-anchor$/.test(n.id||''))hide(n)});['ent-nav-section','ng-enterprise','ent-p2-nav-section','ng-enterprise-p2','sld-navgroup-school','lms-nav-section','acx-nav-item','p3-staff-management-nav'].forEach(function(id){hide(document.getElementById(id))});policy(root)}
function toggle(id){var n=document.getElementById(id);if(!n)return false;var open=n.classList.toggle('open'),b=n.querySelector(':scope > .nav-group-header');if(b)b.setAttribute('aria-expanded',open?'true':'false');return open}
window.EDUTRACK_SCHOOL_SIDEBAR={build:build,applyPolicy:policy,toggle:toggle};
function init(){var lv=get('v43_login_level');if(lv&&lv!=='SCHOOL')return;if(!build()){setTimeout(init,250);return}new MutationObserver(clean).observe(document.getElementById('sidebarScroll'),{childList:true,subtree:true});setInterval(clean,1000);if(typeof window.sidebarInitPaging==='function'){window.sidebarPagingReady=false;window.sidebarInitPaging()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(init,900)});else setTimeout(init,900);
})();
