(function(){'use strict';if(window.__EDUTRACK_SCHOOL_SIDEBAR__)return;window.__EDUTRACK_SCHOOL_SIDEBAR__=true;
function get(k){try{return String(localStorage.getItem(k)||'').toUpperCase()}catch(e){return''}}function esc(v){return String(v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function item(label,icon,action,attrs,target){return'<button type="button" class="nav-item school-nav-item" data-school-nav="'+esc(label)+'" data-school-target="'+esc(target||'action:'+label)+'" data-school-permission="SCHOOL" '+(attrs||'')+' onclick="EDUTRACK_SCHOOL_SIDEBAR.activate(this);'+action+'"><span class="icon">'+icon+'</span><span class="nav-label">'+esc(label)+'</span></button>'}
function page(label,icon,id,after){return item(label,icon,"showPage('"+id+"',this)"+(after?';'+after:''),'','page:'+id)}function sld(label,icon,section){return item(label,icon,"window.EMS_SLD&&EMS_SLD.openSection('"+section+"')",'','section:'+section)}
function api(label,icon,name){return item(label,icon,"window."+name+"&&typeof window."+name+".open==='function'&&window."+name+".open()",'','api:'+name+'.open')}
function fms(label,icon,id){return item(label,icon,"fmsShowPage('"+id+"',this)",'','fms:'+id)}
function group(id,label,icon,children,attrs){return'<div class="nav-group school-nav-group" id="'+id+'" '+(attrs||'')+'><button type="button" class="nav-group-header" onclick="EDUTRACK_SCHOOL_SIDEBAR.toggle(\''+id+'\')" aria-controls="'+id+'-items" aria-expanded="false"><span class="icon">'+icon+'</span><span class="nav-label">'+esc(label)+'</span><span class="nav-group-arrow">▶</span></button><div class="nav-group-items" id="'+id+'-items">'+children.join('')+'</div></div>'}
function result(label,icon,id,renderer,arg){return page(label,icon,id,"setTimeout(function(){window."+renderer+"&&"+renderer+".render("+(arg||'')+");},20)")}
function schoolSession(){var context=window._v43SchoolLoginContext||{};return get('v43_login_level')==='SCHOOL'||String(context.administrativeLevel||context.level||'').toUpperCase()==='SCHOOL'}
function ensureRoot(){var scroll=document.getElementById('sidebarScroll');if(!scroll)return null;var root=document.getElementById('sg-school-level');if(!root){root=document.createElement('div');root.id='sg-school-level';root.className='nav-supergroup open';root.dataset.adminLevel='SCHOOL';root.innerHTML='<button type="button" class="nav-supergroup-header" aria-controls="sg-school-level-items" aria-expanded="true"><span class="icon">🏫</span><span class="nav-label">School Level</span></button><div class="nav-supergroup-items" id="sg-school-level-items"></div>';scroll.insertBefore(root,scroll.firstChild)}var wrap=root.querySelector(':scope > .nav-supergroup-items');if(!wrap){wrap=document.createElement('div');wrap.className='nav-supergroup-items';wrap.id='sg-school-level-items';root.appendChild(wrap)}root.dataset.adminLevel='SCHOOL';root.hidden=false;root.style.removeProperty('display');root.classList.add('open');var header=root.querySelector(':scope > .nav-supergroup-header');if(header){header.setAttribute('aria-expanded','true');header.onclick=function(){root.classList.toggle('open');header.setAttribute('aria-expanded',root.classList.contains('open')?'true':'false')}}if(root.dataset.schoolSidebarReady==='true'&&!wrap.querySelector('.school-nav-item'))delete root.dataset.schoolSidebarReady;return{root:root,wrap:wrap}}
function build(){var host=ensureRoot();if(!host)return false;var root=host.root,wrap=host.wrap;if(root.dataset.schoolSidebarReady==='true'&&wrap.querySelector('.school-nav-item')){policy(root);return true}
var reports=group('school-reports','Reports','📑',[page('School Report Generator','📘','schoolreport','window.SRG&&SRG.render()'),page('Academic Year Report','📚','annualreport','window.SRG_ANNUAL&&SRG_ANNUAL.render()')]);
var fees=group('school-fee-hub','Fee Hub','🏦',[fms('FMS Dashboard','📊','fms-dashboard'),fms('Fee Setup','🏷️','fms-fee-types'),fms('Class Structures','📐','fms-fee-structure'),fms('Record Payment','💳','fms-record-payment'),fms('Receipt Registry','🧾','fms-receipts'),fms('Outstanding Fees','⚠️','fms-outstanding'),fms('Financial Reports','📈','fms-reports-hub')],'data-private-school-feature="true"');
var teacherRegister=group('school-teachers-register','Teachers Register','👨‍🏫',[page('Attendance Register','📋','teachers'),page('Teacher Setup','👥','teachersetup'),page('Term Config','📅','termconfig'),page('Attendance Report','📊','tattendreport'),page('Analytics Dashboard','📈','tattendanalytics'),page('Notifications Log','🔔','tattendnotif'),page('Teacher Alert (5-Day / SISO)','🆘','teachalert5'),page('Teacher Critical Alert (1-Month / HR)','🚨','teachalertmonth')]);
var ht=[page('Subject Config','📚','subjects'),reports,fees,teacherRegister,group('school-system-tools','System Tools','🔧',[page('Integrity Check','🔒','integrity'),page('Cloud Sync','☁️','sync')]),result('Publish Results','🔐','ges-publish-results','GES_RESULT_PUBLISH_UI'),result('Block Result','⛔','ges-block-result','GES_RESULT_BLOCK_UI'),result('Publish Mock Results','🎯','ges-publish-mock-results','GES_MOCK_RESULT_PUBLISH_UI'),result('Block Mock Result','🚫','ges-block-mock-result','GES_MOCK_RESULT_BLOCK_UI')];
var staff=group('school-staff-management','STAFF MANAGEMENT','👥',[sld('User Accounts & Access Control','🔐','access-control'),item('Staff Registry','👥',"window.EDUTRACK_STAFF_MANAGEMENT_PART3&&EDUTRACK_STAFF_MANAGEMENT_PART3.open()",'','api:EDUTRACK_STAFF_MANAGEMENT_PART3.open'),result('Assign Class to Teachers','🧑‍💼','ges-assign-class','GES_TEACHER_ASSIGN_UI',"'assign'"),result('Reassign Class','🔁','ges-assign-class','GES_TEACHER_ASSIGN_UI',"'reassign'"),result('Assign Roles','🧑‍💼','ges-assign-roles','GES_ROLE_ASSIGN_UI')],'data-role-category="Staff Management"');
var admissions=group('school-student-admission','STUDENT ADMISSION','🪪',[page('New Student Admission','➕','gnsis-admission'),item('Transfer Admission','🔁',"window.EMS_GNSIS_LIFE&&EMS_GNSIS_LIFE.open('gnsis-transfer')",'','workflow:gnsis-transfer'),item('Student Search / Profile','🔎',"window.EMS_GNSIS_LIFE&&EMS_GNSIS_LIFE.open('gnsis-search')",'','workflow:gnsis-search'),api('Online Admission','📝','EDUTRACK_ONLINE_ADMISSIONS'),api('Admissions Review','✅','EDUTRACK_ADMISSIONS_REVIEW')]);
var pupils=group('school-pupils-register','Pupils Register','👧',[page('Attendance Register','📋','pupils'),page('Pupil Setup','📋','pupilsetup'),page('SMS Logs','📨','smslogs'),page('Pupils Report','📊','pupilreport'),page('Audit Trail','🔍','pa-audittrail'),page('Attendance Reports','📈','pa-reporting'),page('Automation Hub','⚡','pa-automation'),page('Headteacher Critical Alert (3-Day)','🚨','htcritical')]);
var tc=[page('Score Entry','📝','entry'),page('Multi-Subject Entry','📚','multientry'),page('Mock Entry','📋','mock'),pupils,sld('SHEP Activities','🩺','shep'),sld('Subject Register','📖','subject-register'),sld('Sporting Activities','⚽','sporting'),result('Publish Results','🔐','ges-publish-results','GES_RESULT_PUBLISH_UI'),result('Block Result','⛔','ges-block-result','GES_RESULT_BLOCK_UI'),result('Publish Mock Results','🎯','ges-publish-mock-results','GES_MOCK_RESULT_PUBLISH_UI'),result('Block Mock Result','🚫','ges-block-mock-result','GES_MOCK_RESULT_BLOCK_UI'),page('Learning Management (LMS)','🎓','lms-teacher')];
var shared=[page('Student Database','🧑‍🎓','students'),page('Result Slip','📄','slip'),page('Mock Result','🧪','mockresult'),page('Mock Exam Analysis','🎯','mockanalysis'),page('Broadsheet','📊','broadsheet'),page('Rankings','🏆','rankings'),page('Chart Analysis','📈','analytics'),page('Index Generator','🔢','indexgen')];
var smart=[page('AI Analytics Engine','🤖','ent-ai'),page('Workflow Automation','🔁','ent-workflow'),page('Business Intelligence','📊','ent-bi'),page('Student Health','🏥','ent-health'),page('Library','📚','ent-library'),page('Timetable AI','🗓️','ent-timetable'),page('Procurement','🧾','ent-procurement'),page('Guidance & Counselling','🧑‍🎓','ent-guidance')];
var integrated=[api('Communication Hub','💬','EDUTRACK_COMMUNICATION_HUB'),api('Chat','💬','EDUTRACK_CHAT'),api('Control Panel','📊','EDUTRACK_CONTROL_PANEL'),page('Analytics Narrative','🧠','ges-school',"setTimeout(function(){window.EDUTRACK_ANALYTICS_NARRATIVE&&EDUTRACK_ANALYTICS_NARRATIVE.generate('page-ges-school');},50)"),api('Quiz','📝','EDUTRACK_QUIZ_MODULE'),page('Transport Management','🚌','transport-management'),page('Hostel Management','🏠','hostel-management'),page('QR Attendance','▣','qr-attendance')];
var info='<div class="nav-section school-nav-section school-info-session"><span class="nav-section-label">Info &amp; Session</span></div>'+page('User Guide','📘','user-guide')+page('Copyright','©️','copyright')+page('Acknowledgement','🙏','acknowledgement')+page('Developer','👨‍💻','about')+item('Log Out','🚪','emsDoLogout()','data-school-logout="true"','session:logout');
wrap.innerHTML='<div class="nav-section school-nav-section"><span class="nav-section-label">Overview</span></div>'+page('Dashboard','📊','dashboard')+item('Switch Language','🌐','window.EMS_I18N&&EMS_I18N.openSwitcher()','','api:EMS_I18N.openSwitcher')+page('Setup / Config','⚙️','setup')+group('ng-cat-headteacher','Headteacher','🧑‍💼',ht,'data-role-category="Headteacher"')+staff+admissions+group('ng-cat-teachers','Teachers','👩‍🏫',tc,'data-role-category="Teachers"')+group('ng-cat-shared','Shared','🔗',shared,'data-role-category="Shared"')+group('school-smart-management','SMART SCHOOL MANAGEMENT & INTELLIGENCE','🧠',smart)+group('school-integrated-modules','INTEGRATED SCHOOL MODULES','🔌',integrated)+info+'<div id="school-headteacher-anchor" hidden></div><div id="school-teachers-anchor" hidden></div><div id="school-shared-anchor" hidden></div>';root.dataset.schoolSidebarReady='true';root.classList.add('open');policy(root);return true}
function policy(root){var r=get('v43_login_role').replace(/[^A-Z0-9]+/g,''),ht=document.getElementById('ng-cat-headteacher'),staff=document.getElementById('school-staff-management'),admin=/HEADTEACHER|HEADMASTER|HEADMISTRESS|ASSISTANTHEAD|PROPRIETOR|PROPRIETRESS|SCHOOLADMIN|ADMINISTRATOR/.test(r);if(ht)ht.hidden=!admin;if(staff)staff.hidden=!admin;var cfg=window.CONFIG||{},type=String(cfg.schoolType||cfg.ownershipType||cfg.ownership||'').toUpperCase(),government=/PUBLIC|GOVERNMENT/.test(type);root.querySelectorAll('[data-private-school-feature="true"]').forEach(function(n){n.hidden=government})}
function activateScope(root){if(!schoolSession()||!root)return false;var scroll=document.getElementById('sidebarScroll'),pager=document.getElementById('sidebarPagerBar');if(!scroll)return false;scroll.style.overflowY='auto';Array.prototype.forEach.call(scroll.children,function(n){if(n===root){n.hidden=false;n.style.removeProperty('display');n.dataset.sbPage='1';return}if(n.matches&&n.matches('.nav-supergroup[data-admin-level]')){n.hidden=true;n.style.setProperty('display','none','important')}});root.hidden=false;root.style.removeProperty('display');root.classList.add('open');var header=root.querySelector(':scope > .nav-supergroup-header');if(header)header.setAttribute('aria-expanded','true');if(pager)pager.style.display='none';try{sidebarCurrentPage=1;sidebarTotalPages=1;sidebarPagingReady=true}catch(e){}try{localStorage.setItem('ems_sidebar_page','1')}catch(e){}return root.querySelectorAll('.school-nav-item:not([hidden]),.school-nav-group:not([hidden])').length>0}
function hide(n){if(!n)return;n.hidden=true;n.style.setProperty('display','none','important')}
function clean(){var root=document.getElementById('sg-school-level');if(!root||root.dataset.schoolSidebarReady!=='true')return;var wrap=root.querySelector(':scope > .nav-supergroup-items');if(wrap)Array.prototype.forEach.call(wrap.children,function(n){if(!n.classList.contains('school-nav-item')&&!n.classList.contains('school-nav-group')&&!n.classList.contains('school-nav-section')&&!/^school-(headteacher|teachers|shared)-anchor$/.test(n.id||''))hide(n)});['ent-nav-section','ng-enterprise','ent-p2-nav-section','ng-enterprise-p2','sld-navgroup-school','lms-nav-section','acx-nav-item','p3-staff-management-nav'].forEach(function(id){hide(document.getElementById(id))});var scroll=document.getElementById('sidebarScroll');if(schoolSession()&&scroll)Array.prototype.forEach.call(scroll.children,function(n){if(n===root)return;var label=n.querySelector&&n.querySelector(':scope > .nav-section-label, :scope > .nav-label'),text=label&&label.textContent.trim();if(['Info & Session','User Guide','Copyright','Acknowledgement','Developer','Log Out'].indexOf(text)>=0)hide(n)});policy(root);activateScope(root)}
function toggle(id){var n=document.getElementById(id);if(!n)return false;var open=n.classList.toggle('open'),b=n.querySelector(':scope > .nav-group-header');if(b)b.setAttribute('aria-expanded',open?'true':'false');return open}
function activate(node){var root=document.getElementById('sg-school-level');if(!root||!node)return;root.querySelectorAll('.school-nav-item.active').forEach(function(n){n.classList.remove('active');n.removeAttribute('aria-current')});node.classList.add('active');node.setAttribute('aria-current','page');var parent=node.closest('.school-nav-group');if(parent&&!parent.classList.contains('open'))toggle(parent.id)}
function installStyle(){if(document.getElementById('edutrack-school-sidebar-style'))return;var style=document.createElement('style');style.id='edutrack-school-sidebar-style';style.textContent='#sg-school-level>.nav-supergroup-items{min-width:0}#sg-school-level .school-nav-group{margin:2px 6px;border-radius:8px;overflow:visible}#sg-school-level .nav-group-header,#sg-school-level .school-nav-item{width:100%;min-height:42px;border:0;text-align:left;cursor:pointer;touch-action:manipulation}#sg-school-level .nav-group-header{display:flex;align-items:center;gap:.55rem}#sg-school-level .nav-group-arrow{margin-left:auto;transition:transform .18s ease}#sg-school-level .school-nav-group.open>.nav-group-header .nav-group-arrow{transform:rotate(90deg)}#sg-school-level .school-nav-group>.nav-group-items{display:none;padding:2px 0 5px 12px}#sg-school-level .school-nav-group.open>.nav-group-items{display:block}#sg-school-level .school-nav-item{display:flex;align-items:center;gap:.55rem;white-space:normal;overflow-wrap:anywhere;border-radius:7px}#sg-school-level .school-nav-item.active{background:rgba(17,138,145,.16);box-shadow:inset 3px 0 #118a91;font-weight:700}#sidebar{height:100vh;height:100dvh;display:flex;flex-direction:column}#sidebar,#sidebarScroll{overflow-x:hidden!important;overscroll-behavior:contain}#sidebarScroll{flex:1;min-height:0;overflow-y:auto!important;scrollbar-gutter:stable}#sidebarPagerBar{display:none} @media(max-width:700px){#sg-school-level .nav-group-header,#sg-school-level .school-nav-item{min-height:48px}#sg-school-level .school-nav-group{margin:3px 5px}} @media(prefers-reduced-motion:reduce){#sg-school-level .nav-group-arrow{transition:none}}';document.head.appendChild(style)}
function refresh(){installStyle();if(!build())return false;var root=document.getElementById('sg-school-level');clean();return activateScope(root)}
window.EDUTRACK_SCHOOL_SIDEBAR={build:build,ensureRoot:ensureRoot,refresh:refresh,applyPolicy:policy,activateScope:activateScope,toggle:toggle,activate:activate};
function init(){installStyle();if(!build()){setTimeout(init,250);return}var root=document.getElementById('sg-school-level'),scroll=document.getElementById('sidebarScroll'),sidebar=document.getElementById('sidebar');if(scroll){scroll.style.overflowX='hidden';scroll.style.overflowY='auto';scroll.style.webkitOverflowScrolling='touch';new MutationObserver(function(){if(!document.getElementById('sg-school-level')||!document.querySelector('#sg-school-level .school-nav-item'))refresh();else clean()}).observe(scroll,{childList:true,subtree:true})}if(sidebar){sidebar.style.overflowY='auto';sidebar.style.overscrollBehavior='contain';sidebar.style.webkitOverflowScrolling='touch'}clean();activateScope(root);setInterval(function(){if(schoolSession())refresh();else clean()},1000)}
window.addEventListener('edutrack:school-session',refresh);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(init,900)});else setTimeout(init,900);
})();
