'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const html = fs.readFileSync(require.resolve('../index.html'), 'utf8');
const footer = html.match(/<div class="sub-modal-footer" id="subv2-renew-footer">[\s\S]*?<\/div>/)?.[0];
assert.ok(footer, 'renewal footer must remain present');
assert.match(footer, /subEntryOpen\(\)/, 'Back action must remain present');
assert.doesNotMatch(footer, /subv2RenewSubmit\(\)|Renew Subscription/, 'footer must not contain the removed renewal action');
assert.match(html, /subv2-renew-pay-btn/, 'Paystack payment action must remain available in the payment panel');
console.log('Renewal footer regression suite passed.');
