'use strict';
const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');const {S3Client,PutObjectCommand,GetObjectCommand,DeleteObjectCommand}=require('@aws-sdk/client-s3');
function mode(){return String(process.env.EDUTRACK_STORAGE_MODE||'local').toLowerCase()}
function production(){return process.env.NODE_ENV==='production'}
function validate(){const m=mode();if(!['local','s3'].includes(m))throw new Error('EDUTRACK_STORAGE_MODE must be local or s3');if(production()&&m!=='s3')throw new Error('Production requires EDUTRACK_STORAGE_MODE=s3 for durable private file storage.');if(m==='s3'&&!process.env.EDUTRACK_STORAGE_BUCKET)throw new Error('EDUTRACK_STORAGE_BUCKET is required when EDUTRACK_STORAGE_MODE=s3.');return m}
let client;
function s3(){if(!client)client=new S3Client({region:process.env.EDUTRACK_STORAGE_REGION||'us-east-1',endpoint:process.env.EDUTRACK_STORAGE_ENDPOINT||undefined,forcePathStyle:process.env.EDUTRACK_STORAGE_FORCE_PATH_STYLE==='true'});return client}
function name(ext){return `${crypto.randomBytes(18).toString('base64url')}${ext}`}
async function put({extension,buffer,mimeType}){const m=validate();const storageName=name(extension);if(m==='local'){const root=path.resolve(process.env.EDUTRACK_LOCAL_STORAGE_DIR||path.join(process.cwd(),'data','uploads'));fs.mkdirSync(root,{recursive:true,mode:0o700});fs.writeFileSync(path.join(root,storageName),buffer,{mode:0o600,flag:'wx'});return{storageName}}await s3().send(new PutObjectCommand({Bucket:process.env.EDUTRACK_STORAGE_BUCKET,Key:storageName,Body:buffer,ContentType:mimeType,ServerSideEncryption:process.env.EDUTRACK_STORAGE_SSE||'AES256'}));return{storageName}}
async function get(storageName){const m=validate();if(m==='local'){const root=path.resolve(process.env.EDUTRACK_LOCAL_STORAGE_DIR||path.join(process.cwd(),'data','uploads'));const target=path.resolve(root,storageName);if(path.dirname(target)!==root||!fs.existsSync(target))return null;return{stream:fs.createReadStream(target)}}const result=await s3().send(new GetObjectCommand({Bucket:process.env.EDUTRACK_STORAGE_BUCKET,Key:storageName}));return{stream:result.Body}}
async function remove(storageName){if(mode()==='local'){const root=path.resolve(process.env.EDUTRACK_LOCAL_STORAGE_DIR||path.join(process.cwd(),'data','uploads'));const target=path.resolve(root,storageName);if(path.dirname(target)===root)fs.rmSync(target,{force:true});return}await s3().send(new DeleteObjectCommand({Bucket:process.env.EDUTRACK_STORAGE_BUCKET,Key:storageName}))}
module.exports={mode,validate,put,get,remove};
