'use strict';

const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const mysql = require('mysql2/promise');

const DATABASE_URL = process.env.EDUTRACK_DATABASE_URL || process.env.DATABASE_URL || '';
const SCHEMA_VERSION = 8;
let pool;
let initialized;

function isConfigured() { return Boolean(DATABASE_URL); }
function requireConfigured() { if (!isConfigured()) throw new Error('EDUTRACK_DATABASE_URL is required for the relational authority layer'); }
function getPool() {
  requireConfigured();
  if (!pool) pool = mysql.createPool({ uri: DATABASE_URL, waitForConnections: true, connectionLimit: Number(process.env.EDUTRACK_DB_POOL_SIZE || 5), queueLimit: 0, multipleStatements: false, decimalNumbers: true });
  return pool;
}
function newId(prefix) { return `${prefix}_${crypto.randomBytes(12).toString('hex')}`; }
function iso(value) { return value ? new Date(value).toISOString().slice(0, 19).replace('T', ' ') : null; }
function json(value) { return JSON.stringify(value == null ? null : value); }
function parseJson(value, fallback) { try { if (value == null) return fallback; if (typeof value === 'object') return value; return JSON.parse(value); } catch { return fallback; } }

const TABLES = [
  `CREATE TABLE IF NOT EXISTS schema_migrations (version INT PRIMARY KEY, name VARCHAR(160) NOT NULL, applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS users (id VARCHAR(80) PRIMARY KEY, email VARCHAR(254) NOT NULL UNIQUE, staff_id VARCHAR(120) NULL UNIQUE, status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE', active BOOLEAN NOT NULL DEFAULT TRUE, development_fixture BOOLEAN NOT NULL DEFAULT FALSE, hierarchy VARCHAR(80) NULL, scope_json JSON NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, revoked_at TIMESTAMP NULL) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS credentials (id VARCHAR(80) PRIMARY KEY, user_id VARCHAR(80) NOT NULL, password_hash TEXT NOT NULL, access_code_hash TEXT NULL, status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY credentials_user_unique (user_id), CONSTRAINT credentials_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS roles (id VARCHAR(80) PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE, description VARCHAR(255) NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS permissions (id VARCHAR(100) PRIMARY KEY, name VARCHAR(120) NOT NULL UNIQUE, description VARCHAR(255) NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS role_permissions (role_id VARCHAR(80) NOT NULL, permission_id VARCHAR(100) NOT NULL, PRIMARY KEY (role_id, permission_id), CONSTRAINT role_permissions_role_fk FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE, CONSTRAINT role_permissions_permission_fk FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS user_roles (user_id VARCHAR(80) NOT NULL, role_id VARCHAR(80) NOT NULL, assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (user_id, role_id), CONSTRAINT user_roles_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT user_roles_role_fk FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS tenants (id VARCHAR(80) PRIMARY KEY, name VARCHAR(180) NOT NULL, tenant_type VARCHAR(40) NOT NULL, parent_id VARCHAR(80) NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, CONSTRAINT tenants_parent_fk FOREIGN KEY (parent_id) REFERENCES tenants(id) ON DELETE SET NULL) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS tenant_memberships (user_id VARCHAR(80) NOT NULL, tenant_id VARCHAR(80) NOT NULL, scope_json JSON NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (user_id, tenant_id), CONSTRAINT memberships_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT memberships_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS regions (id VARCHAR(80) PRIMARY KEY, name VARCHAR(180) NOT NULL UNIQUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS districts (id VARCHAR(80) PRIMARY KEY, region_id VARCHAR(80) NOT NULL, name VARCHAR(180) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY district_region_name (region_id, name), CONSTRAINT districts_region_fk FOREIGN KEY (region_id) REFERENCES regions(id) ON DELETE RESTRICT) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS schools (id VARCHAR(80) PRIMARY KEY, tenant_id VARCHAR(80) NULL, district_id VARCHAR(80) NULL, name VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT schools_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL, CONSTRAINT schools_district_fk FOREIGN KEY (district_id) REFERENCES districts(id) ON DELETE SET NULL) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS server_sessions (id VARCHAR(80) PRIMARY KEY, token_hash CHAR(64) NOT NULL UNIQUE, user_id VARCHAR(80) NOT NULL, created_at TIMESTAMP NOT NULL, expires_at TIMESTAMP NOT NULL, revoked_at TIMESTAMP NULL, csrf_token_hash CHAR(64) NULL, CONSTRAINT sessions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS audit_events (id VARCHAR(80) PRIMARY KEY, event_type VARCHAR(120) NOT NULL, actor_user_id VARCHAR(80) NULL, occurred_at TIMESTAMP NOT NULL, correlation_id VARCHAR(160) NULL, ip VARCHAR(80) NULL, user_agent VARCHAR(300) NULL, metadata_json JSON NULL, CONSTRAINT audit_actor_fk FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS staff (id VARCHAR(80) PRIMARY KEY, user_id VARCHAR(80) NULL, staff_identifier VARCHAR(120) NOT NULL UNIQUE, full_name VARCHAR(255) NOT NULL, phone VARCHAR(80) NULL, email VARCHAR(254) NULL, staff_type VARCHAR(80) NOT NULL DEFAULT 'STAFF', status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE', tenant_id VARCHAR(80) NOT NULL, region_id VARCHAR(80) NULL, district_id VARCHAR(80) NULL, school_id VARCHAR(80) NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY staff_user_unique (user_id), CONSTRAINT staff_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL, CONSTRAINT staff_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT, CONSTRAINT staff_region_fk FOREIGN KEY (region_id) REFERENCES regions(id) ON DELETE SET NULL, CONSTRAINT staff_district_fk FOREIGN KEY (district_id) REFERENCES districts(id) ON DELETE SET NULL, CONSTRAINT staff_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS students (id VARCHAR(80) PRIMARY KEY, admission_number VARCHAR(120) NOT NULL UNIQUE, student_identifier VARCHAR(120) NOT NULL UNIQUE, full_name VARCHAR(255) NOT NULL, date_of_birth DATE NULL, gender VARCHAR(40) NULL, tenant_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, class_id VARCHAR(80) NULL, admission_date DATE NULL, special_needs TEXT NULL, emergency_contact VARCHAR(255) NULL, status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, CONSTRAINT students_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT, CONSTRAINT students_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS classes (id VARCHAR(80) PRIMARY KEY, name VARCHAR(160) NOT NULL, school_id VARCHAR(80) NOT NULL, tenant_id VARCHAR(80) NOT NULL, academic_config_ref VARCHAR(120) NULL, status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY class_school_name (school_id,name), CONSTRAINT classes_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT, CONSTRAINT classes_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS parent_student_relationships (parent_user_id VARCHAR(80) NOT NULL, student_id VARCHAR(80) NOT NULL, relationship_type VARCHAR(80) NOT NULL DEFAULT 'PARENT', active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL, PRIMARY KEY (parent_user_id,student_id), CONSTRAINT ps_parent_fk FOREIGN KEY (parent_user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT ps_student_fk FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS staff_school_assignments (staff_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, assigned_at TIMESTAMP NOT NULL, PRIMARY KEY (staff_id,school_id), CONSTRAINT ssa_staff_fk FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE, CONSTRAINT ssa_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS teacher_class_assignments (staff_id VARCHAR(80) NOT NULL, class_id VARCHAR(80) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, assigned_at TIMESTAMP NOT NULL, PRIMARY KEY (staff_id,class_id), CONSTRAINT tca_staff_fk FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE, CONSTRAINT tca_class_fk FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE) ENGINE=InnoDB`
];
const PART31_TABLES = [
  `CREATE TABLE IF NOT EXISTS payment_intents (id VARCHAR(80) PRIMARY KEY, reference VARCHAR(120) NOT NULL UNIQUE, idempotency_key VARCHAR(120) NOT NULL, user_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NULL, plan_id VARCHAR(80) NOT NULL, amount DECIMAL(12,2) NOT NULL, currency VARCHAR(12) NOT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY payment_intent_user_key (user_id,idempotency_key), KEY payment_intent_school (school_id), CONSTRAINT payment_intent_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT, CONSTRAINT payment_intent_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS payment_transactions (id VARCHAR(80) PRIMARY KEY, reference VARCHAR(120) NOT NULL UNIQUE, intent_id VARCHAR(80) NULL, user_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NULL, plan_id VARCHAR(80) NOT NULL, amount DECIMAL(12,2) NOT NULL, currency VARCHAR(12) NOT NULL, status VARCHAR(32) NOT NULL, provider_event_id VARCHAR(160) NULL, created_at TIMESTAMP NOT NULL, UNIQUE KEY payment_tx_event (provider_event_id), KEY payment_tx_user (user_id), KEY payment_tx_school_status (school_id,status), CONSTRAINT payment_tx_intent_fk FOREIGN KEY (intent_id) REFERENCES payment_intents(id) ON DELETE SET NULL, CONSTRAINT payment_tx_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT, CONSTRAINT payment_tx_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS subscriptions (id VARCHAR(80) PRIMARY KEY, user_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NULL, plan_id VARCHAR(80) NOT NULL, status VARCHAR(32) NOT NULL, starts_at TIMESTAMP NOT NULL, expires_at TIMESTAMP NOT NULL, payment_reference VARCHAR(120) NULL, last_transaction_id VARCHAR(80) NULL, renewal_state VARCHAR(32) NOT NULL DEFAULT 'INITIAL', created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, KEY subscription_user_status (user_id,status), KEY subscription_school_status (school_id,status), KEY subscription_expiry (expires_at), CONSTRAINT subscription_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT, CONSTRAINT subscription_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL, CONSTRAINT subscription_tx_fk FOREIGN KEY (last_transaction_id) REFERENCES payment_transactions(id) ON DELETE SET NULL) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS payment_events (id VARCHAR(80) PRIMARY KEY, event_id VARCHAR(160) NOT NULL UNIQUE, reference VARCHAR(120) NOT NULL, event_type VARCHAR(80) NOT NULL, payload_json JSON NULL, received_at TIMESTAMP NOT NULL, KEY payment_event_reference (reference), CONSTRAINT payment_event_tx_fk FOREIGN KEY (reference) REFERENCES payment_transactions(reference) ON DELETE RESTRICT) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS password_reset_records (id VARCHAR(80) PRIMARY KEY, user_id VARCHAR(80) NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE, created_at TIMESTAMP NOT NULL, expires_at TIMESTAMP NOT NULL, used_at TIMESTAMP NULL, KEY reset_user_expiry (user_id,expires_at), CONSTRAINT reset_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS file_records (id VARCHAR(80) PRIMARY KEY, owner_user_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NULL, storage_name VARCHAR(255) NOT NULL UNIQUE, original_name VARCHAR(255) NOT NULL, mime_type VARCHAR(120) NOT NULL, size_bytes BIGINT NOT NULL, category VARCHAR(80) NOT NULL, associated_entity VARCHAR(160) NULL, created_at TIMESTAMP NOT NULL, KEY file_owner (owner_user_id), KEY file_school (school_id), CONSTRAINT file_owner_fk FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE RESTRICT, CONSTRAINT file_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL) ENGINE=InnoDB`
];
const ACADEMIC_TABLES = [
  `CREATE TABLE IF NOT EXISTS academic_configurations (id VARCHAR(80) PRIMARY KEY, tenant_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, academic_year VARCHAR(32) NOT NULL, term VARCHAR(64) NOT NULL, week INT NULL, opening_date DATE NOT NULL, closing_date DATE NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'DRAFT', metadata_json JSON NULL, created_by VARCHAR(80) NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY academic_config_unique (school_id,academic_year,term), CONSTRAINT acad_cfg_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT, CONSTRAINT acad_cfg_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT, CONSTRAINT acad_cfg_creator_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL, CHECK (closing_date >= opening_date)) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS subjects (id VARCHAR(80) PRIMARY KEY, tenant_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, code VARCHAR(64) NOT NULL, name VARCHAR(180) NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE', metadata_json JSON NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY subject_school_code (school_id,code), CONSTRAINT subjects_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT, CONSTRAINT subjects_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS school_subjects (school_id VARCHAR(80) NOT NULL, subject_id VARCHAR(80) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, PRIMARY KEY (school_id,subject_id), CONSTRAINT school_subject_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE, CONSTRAINT school_subject_subject_fk FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS teacher_subject_assignments (staff_id VARCHAR(80) NOT NULL, subject_id VARCHAR(80) NOT NULL, class_id VARCHAR(80) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, assigned_at TIMESTAMP NOT NULL, PRIMARY KEY (staff_id,subject_id,class_id), CONSTRAINT tsa_staff_fk FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE, CONSTRAINT tsa_subject_fk FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE, CONSTRAINT tsa_class_fk FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS attendance_registers (id VARCHAR(80) PRIMARY KEY, tenant_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, class_id VARCHAR(80) NOT NULL, academic_config_id VARCHAR(80) NULL, attendance_date DATE NOT NULL, register_type VARCHAR(32) NOT NULL DEFAULT 'STUDENT', created_by VARCHAR(80) NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY attendance_register_unique (class_id,attendance_date,register_type), CONSTRAINT ar_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT, CONSTRAINT ar_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT, CONSTRAINT ar_class_fk FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE RESTRICT, CONSTRAINT ar_config_fk FOREIGN KEY (academic_config_id) REFERENCES academic_configurations(id) ON DELETE SET NULL, CONSTRAINT ar_creator_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS student_attendance_records (id VARCHAR(80) PRIMARY KEY, register_id VARCHAR(80) NOT NULL, student_id VARCHAR(80) NOT NULL, status VARCHAR(24) NOT NULL, note VARCHAR(255) NULL, recorded_by VARCHAR(80) NULL, recorded_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY student_attendance_unique (register_id,student_id), CONSTRAINT sar_register_fk FOREIGN KEY (register_id) REFERENCES attendance_registers(id) ON DELETE CASCADE, CONSTRAINT sar_student_fk FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE RESTRICT, CONSTRAINT sar_recorder_fk FOREIGN KEY (recorded_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS teacher_attendance_records (id VARCHAR(80) PRIMARY KEY, tenant_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, staff_id VARCHAR(80) NOT NULL, attendance_date DATE NOT NULL, status VARCHAR(24) NOT NULL, sign_in TIME NULL, sign_out TIME NULL, note VARCHAR(255) NULL, recorded_by VARCHAR(80) NULL, recorded_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY teacher_attendance_unique (staff_id,attendance_date), CONSTRAINT tar_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT, CONSTRAINT tar_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT, CONSTRAINT tar_staff_fk FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE RESTRICT, CONSTRAINT tar_recorder_fk FOREIGN KEY (recorded_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS examination_types (id VARCHAR(80) PRIMARY KEY, tenant_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, name VARCHAR(120) NOT NULL, category VARCHAR(32) NOT NULL DEFAULT 'NORMAL', status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE', UNIQUE KEY examination_type_school_name (school_id,name), CONSTRAINT et_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT, CONSTRAINT et_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS examinations (id VARCHAR(80) PRIMARY KEY, tenant_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, class_id VARCHAR(80) NOT NULL, academic_config_id VARCHAR(80) NOT NULL, examination_type_id VARCHAR(80) NOT NULL, name VARCHAR(180) NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'DRAFT', publication_status VARCHAR(32) NOT NULL DEFAULT 'UNPUBLISHED', created_by VARCHAR(80) NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY examination_school_name (school_id,class_id,academic_config_id,name), CONSTRAINT exam_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT, CONSTRAINT exam_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT, CONSTRAINT exam_class_fk FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE RESTRICT, CONSTRAINT exam_config_fk FOREIGN KEY (academic_config_id) REFERENCES academic_configurations(id) ON DELETE RESTRICT, CONSTRAINT exam_type_fk FOREIGN KEY (examination_type_id) REFERENCES examination_types(id) ON DELETE RESTRICT, CONSTRAINT exam_creator_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS examination_components (id VARCHAR(80) PRIMARY KEY, examination_id VARCHAR(80) NOT NULL, subject_id VARCHAR(80) NOT NULL, name VARCHAR(180) NOT NULL, maximum_score DECIMAL(8,2) NOT NULL, position_no INT NOT NULL DEFAULT 1, UNIQUE KEY exam_component_unique (examination_id,subject_id,name), CONSTRAINT ec_exam_fk FOREIGN KEY (examination_id) REFERENCES examinations(id) ON DELETE CASCADE, CONSTRAINT ec_subject_fk FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE RESTRICT, CHECK (maximum_score > 0)) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS scores (id VARCHAR(80) PRIMARY KEY, tenant_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, class_id VARCHAR(80) NOT NULL, student_id VARCHAR(80) NOT NULL, subject_id VARCHAR(80) NOT NULL, examination_id VARCHAR(80) NOT NULL, component_id VARCHAR(80) NOT NULL, raw_score DECIMAL(8,2) NOT NULL, maximum_score DECIMAL(8,2) NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'DRAFT', entered_by VARCHAR(80) NULL, entered_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY score_unique (student_id,component_id), CONSTRAINT score_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT, CONSTRAINT score_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT, CONSTRAINT score_class_fk FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE RESTRICT, CONSTRAINT score_student_fk FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE RESTRICT, CONSTRAINT score_subject_fk FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE RESTRICT, CONSTRAINT score_exam_fk FOREIGN KEY (examination_id) REFERENCES examinations(id) ON DELETE RESTRICT, CONSTRAINT score_component_fk FOREIGN KEY (component_id) REFERENCES examination_components(id) ON DELETE RESTRICT, CONSTRAINT score_enterer_fk FOREIGN KEY (entered_by) REFERENCES users(id) ON DELETE SET NULL, CHECK (raw_score >= 0 AND raw_score <= maximum_score)) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS published_results (id VARCHAR(80) PRIMARY KEY, tenant_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, class_id VARCHAR(80) NOT NULL, student_id VARCHAR(80) NOT NULL, academic_config_id VARCHAR(80) NOT NULL, examination_id VARCHAR(80) NOT NULL, version_no INT NOT NULL DEFAULT 1, result_json JSON NOT NULL, publication_status VARCHAR(32) NOT NULL DEFAULT 'PUBLISHED', published_by VARCHAR(80) NULL, published_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY published_result_unique (student_id,examination_id,version_no), CONSTRAINT pr_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT, CONSTRAINT pr_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT, CONSTRAINT pr_class_fk FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE RESTRICT, CONSTRAINT pr_student_fk FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE RESTRICT, CONSTRAINT pr_config_fk FOREIGN KEY (academic_config_id) REFERENCES academic_configurations(id) ON DELETE RESTRICT, CONSTRAINT pr_exam_fk FOREIGN KEY (examination_id) REFERENCES examinations(id) ON DELETE RESTRICT, CONSTRAINT pr_publisher_fk FOREIGN KEY (published_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS result_slips (id VARCHAR(80) PRIMARY KEY, published_result_id VARCHAR(80) NOT NULL UNIQUE, issued_at TIMESTAMP NOT NULL, metadata_json JSON NULL, CONSTRAINT rs_result_fk FOREIGN KEY (published_result_id) REFERENCES published_results(id) ON DELETE CASCADE) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS broadsheets (id VARCHAR(80) PRIMARY KEY, tenant_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, class_id VARCHAR(80) NOT NULL, academic_config_id VARCHAR(80) NOT NULL, examination_id VARCHAR(80) NOT NULL, format_code VARCHAR(8) NOT NULL DEFAULT 'A', snapshot_json JSON NOT NULL, created_by VARCHAR(80) NULL, created_at TIMESTAMP NOT NULL, UNIQUE KEY broadsheet_unique (class_id,examination_id,format_code), CONSTRAINT bs_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT, CONSTRAINT bs_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT, CONSTRAINT bs_class_fk FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE RESTRICT, CONSTRAINT bs_config_fk FOREIGN KEY (academic_config_id) REFERENCES academic_configurations(id) ON DELETE RESTRICT, CONSTRAINT bs_exam_fk FOREIGN KEY (examination_id) REFERENCES examinations(id) ON DELETE RESTRICT, CONSTRAINT bs_creator_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS promotion_records (id VARCHAR(80) PRIMARY KEY, tenant_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, student_id VARCHAR(80) NOT NULL, source_class_id VARCHAR(80) NOT NULL, destination_class_id VARCHAR(80) NOT NULL, academic_config_id VARCHAR(80) NOT NULL, decision VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'DRAFT', decided_by VARCHAR(80) NULL, decided_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY promotion_unique (student_id,academic_config_id), CONSTRAINT promo_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT, CONSTRAINT promo_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT, CONSTRAINT promo_student_fk FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE RESTRICT, CONSTRAINT promo_source_fk FOREIGN KEY (source_class_id) REFERENCES classes(id) ON DELETE RESTRICT, CONSTRAINT promo_dest_fk FOREIGN KEY (destination_class_id) REFERENCES classes(id) ON DELETE RESTRICT, CONSTRAINT promo_config_fk FOREIGN KEY (academic_config_id) REFERENCES academic_configurations(id) ON DELETE RESTRICT, CONSTRAINT promo_decider_fk FOREIGN KEY (decided_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS mock_examinations (id VARCHAR(80) PRIMARY KEY, tenant_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, class_id VARCHAR(80) NOT NULL, academic_config_id VARCHAR(80) NOT NULL, label VARCHAR(64) NOT NULL, format_code VARCHAR(8) NOT NULL DEFAULT 'B', status VARCHAR(32) NOT NULL DEFAULT 'DRAFT', publication_status VARCHAR(32) NOT NULL DEFAULT 'UNPUBLISHED', created_by VARCHAR(80) NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY mock_exam_unique (class_id,academic_config_id,label), CONSTRAINT mock_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT, CONSTRAINT mock_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT, CONSTRAINT mock_class_fk FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE RESTRICT, CONSTRAINT mock_config_fk FOREIGN KEY (academic_config_id) REFERENCES academic_configurations(id) ON DELETE RESTRICT, CONSTRAINT mock_creator_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS mock_components (id VARCHAR(80) PRIMARY KEY, mock_examination_id VARCHAR(80) NOT NULL, subject_id VARCHAR(80) NOT NULL, name VARCHAR(180) NOT NULL, maximum_score DECIMAL(8,2) NOT NULL, UNIQUE KEY mock_component_unique (mock_examination_id,subject_id,name), CONSTRAINT mc_mock_fk FOREIGN KEY (mock_examination_id) REFERENCES mock_examinations(id) ON DELETE CASCADE, CONSTRAINT mc_subject_fk FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE RESTRICT) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS mock_scores (id VARCHAR(80) PRIMARY KEY, mock_examination_id VARCHAR(80) NOT NULL, component_id VARCHAR(80) NOT NULL, student_id VARCHAR(80) NOT NULL, raw_score DECIMAL(8,2) NOT NULL, maximum_score DECIMAL(8,2) NOT NULL, entered_by VARCHAR(80) NULL, entered_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY mock_score_unique (student_id,component_id), CONSTRAINT ms_mock_fk FOREIGN KEY (mock_examination_id) REFERENCES mock_examinations(id) ON DELETE CASCADE, CONSTRAINT ms_component_fk FOREIGN KEY (component_id) REFERENCES mock_components(id) ON DELETE RESTRICT, CONSTRAINT ms_student_fk FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE RESTRICT, CONSTRAINT ms_enterer_fk FOREIGN KEY (entered_by) REFERENCES users(id) ON DELETE SET NULL, CHECK (raw_score >= 0 AND raw_score <= maximum_score)) ENGINE=InnoDB`,
  `CREATE TABLE IF NOT EXISTS academic_report_snapshots (id VARCHAR(80) PRIMARY KEY, tenant_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NULL, class_id VARCHAR(80) NULL, report_type VARCHAR(80) NOT NULL, filter_json JSON NULL, snapshot_json JSON NOT NULL, created_by VARCHAR(80) NULL, created_at TIMESTAMP NOT NULL, INDEX academic_report_scope (tenant_id,school_id,class_id,report_type,created_at), CONSTRAINT ars_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT, CONSTRAINT ars_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL, CONSTRAINT ars_class_fk FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE SET NULL, CONSTRAINT ars_creator_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB`
];

const ROLE_SEED = ['DEVELOPER_ROOT','SUPER_ADMIN','NATIONAL_ADMIN','REGIONAL_ADMIN','DISTRICT_ADMIN','HEADTEACHER','TEACHER','PARENT','STUDENT'];
const PERMISSION_SEED = ['auth.session.manage','admin.summary.read','security.audit.read','users.manage','roles.manage','tenants.manage','schools.manage','staff.manage','students.manage','academics.manage','attendance.manage','classes.manage','examinations.manage','scores.manage','results.manage','promotion.manage','subscriptions.manage','payments.manage','reporting.read','scope.read','files.manage','files.read','ai.use'];
const ROLE_PERMISSION_SEED = {
  DEVELOPER_ROOT: PERMISSION_SEED,
  SUPER_ADMIN: PERMISSION_SEED.filter((permission) => permission !== 'roles.manage'),
  NATIONAL_ADMIN: ['admin.summary.read','schools.manage','staff.manage','students.manage','academics.manage','attendance.manage','classes.manage','examinations.manage','scores.manage','results.manage','promotion.manage','reporting.read','scope.read'],
  REGIONAL_ADMIN: ['admin.summary.read','schools.manage','staff.manage','students.manage','academics.manage','attendance.manage','classes.manage','examinations.manage','scores.manage','results.manage','promotion.manage','reporting.read','scope.read'],
  DISTRICT_ADMIN: ['admin.summary.read','schools.manage','staff.manage','students.manage','academics.manage','attendance.manage','classes.manage','examinations.manage','scores.manage','results.manage','promotion.manage','reporting.read','scope.read'],
  HEADTEACHER: ['schools.manage','staff.manage','students.manage','academics.manage','attendance.manage','classes.manage','examinations.manage','scores.manage','results.manage','promotion.manage','reporting.read','scope.read'],
  TEACHER: ['students.manage','academics.manage','attendance.manage','classes.manage','examinations.manage','scores.manage','results.manage','reporting.read','scope.read'],
  PARENT: ['reporting.read','scope.read'],
  STUDENT: ['reporting.read','scope.read']
};

async function migrate() {
  requireConfigured();
  const db = getPool();
  const conn = await db.getConnection();
  try {
    await conn.beginTransaction();
    await conn.query(TABLES[0]);
    const [rows] = await conn.query('SELECT version FROM schema_migrations WHERE version = ?', [SCHEMA_VERSION]);
    if (!rows.length) {
      for (const statement of TABLES.slice(1)) await conn.query(statement);
      for (const statement of ACADEMIC_TABLES) await conn.query(statement);
      for (const statement of PART31_TABLES) await conn.query(statement);
      for (const role of ROLE_SEED) await conn.query('INSERT INTO roles (id, name, description) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE name = VALUES(name)', [`role_${role.toLowerCase()}`, role, `Canonical EduTrack role ${role}`]);
      for (const permission of PERMISSION_SEED) await conn.query('INSERT INTO permissions (id, name, description) VALUES (?, ?, ?) ON DUPLICATE KEY UPDATE name = VALUES(name)', [permission, permission, `EduTrack permission ${permission}`]);
      for (const [role, permissions] of Object.entries(ROLE_PERMISSION_SEED)) for (const permission of permissions) await conn.query('INSERT IGNORE INTO role_permissions (role_id, permission_id) VALUES (?, ?)', [`role_${role.toLowerCase()}`, permission]);
      await conn.query('ALTER TABLE teacher_attendance_records ADD COLUMN sign_in TIME NULL, ADD COLUMN sign_out TIME NULL').catch(() => {});
      await conn.query('ALTER TABLE schools ADD COLUMN school_code VARCHAR(120) NULL, ADD COLUMN ownership_type VARCHAR(32) NOT NULL DEFAULT \'PRIVATE\', ADD COLUMN address VARCHAR(255) NULL, ADD COLUMN contact_phone VARCHAR(80) NULL, ADD COLUMN contact_email VARCHAR(254) NULL, ADD COLUMN registration_metadata JSON NULL, ADD UNIQUE KEY schools_code_unique (school_code)').catch(() => {});
      await conn.query('INSERT INTO schema_migrations (version, name) VALUES (?, ?)', [SCHEMA_VERSION, 'part31-production-persistence-migration']);
    }
    await conn.commit();
  } catch (error) { await conn.rollback(); throw error; } finally { conn.release(); }
}
async function ensureInitialized() { if (!isConfigured()) return false; if (!initialized) initialized = migrate().catch((error) => { initialized = null; throw error; }); await initialized; return true; }

function rowToUser(row, credential) {
  if (!row) return null;
  return { id: row.id, email: row.email, staffId: row.staff_id, passwordHash: credential?.password_hash || '', accessCodeHash: credential?.access_code_hash || '', role: row.role_name || null, hierarchy: row.hierarchy, scope: parseJson(row.scope_json, null), active: Boolean(row.active), developmentFixture: Boolean(row.development_fixture), failedLoginCount: 0, lockedUntil: null, createdAt: row.created_at, updatedAt: row.updated_at };
}
async function findUser(identifier) {
  await ensureInitialized();
  const [rows] = await getPool().query(`SELECT u.*, c.password_hash, c.access_code_hash, r.name AS role_name, COALESCE(u.scope_json, tm.scope_json) AS scope_json FROM users u JOIN credentials c ON c.user_id = u.id LEFT JOIN user_roles ur ON ur.user_id = u.id LEFT JOIN roles r ON r.id = ur.role_id LEFT JOIN tenant_memberships tm ON tm.user_id = u.id AND tm.active = TRUE WHERE u.active = TRUE AND LOWER(u.email) = LOWER(?) LIMIT 1`, [identifier]);
  return rowToUser(rows[0], rows[0]);
}
async function findUserById(userId){await ensureInitialized();const [rows]=await getPool().query(`SELECT u.*, c.password_hash, c.access_code_hash, r.name AS role_name FROM users u JOIN credentials c ON c.user_id=u.id LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id WHERE u.id=? AND u.active=TRUE LIMIT 1`,[userId]);return rowToUser(rows[0],rows[0]);}
async function upsertUser(user) {
  await ensureInitialized();
  const now = iso(user.updatedAt || new Date()); const created = iso(user.createdAt || now);
  const db = getPool();
  await db.query(`INSERT INTO users (id,email,staff_id,status,active,development_fixture,hierarchy,scope_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE email=VALUES(email),staff_id=VALUES(staff_id),status=VALUES(status),active=VALUES(active),development_fixture=VALUES(development_fixture),hierarchy=VALUES(hierarchy),scope_json=VALUES(scope_json),updated_at=VALUES(updated_at)`, [user.id, user.email, user.staffId || null, user.active === false ? 'INACTIVE' : 'ACTIVE', user.active !== false, Boolean(user.developmentFixture), user.hierarchy || null, json(user.scope || null), created, now]);
  await db.query(`INSERT INTO credentials (id,user_id,password_hash,access_code_hash,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE password_hash=VALUES(password_hash),access_code_hash=VALUES(access_code_hash),status=VALUES(status),updated_at=VALUES(updated_at)`, [user.credentialId || newId('cred'), user.id, user.passwordHash, user.accessCodeHash || null, 'ACTIVE', created, now]);
  const role = user.role || 'DEVELOPER_ROOT';
  await db.query('INSERT INTO roles (id,name,description) VALUES (?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name)', [`role_${role.toLowerCase()}`, role, `Canonical EduTrack role ${role}`]);
  await db.query('INSERT INTO user_roles (user_id,role_id) VALUES (?,?) ON DUPLICATE KEY UPDATE role_id=VALUES(role_id)', [user.id, `role_${role.toLowerCase()}`]);
  return user;
}
async function provisionDevelopmentAccount(user) { return upsertUser({ ...user, developmentFixture: true, staffId: user.staffId || 'DEV-ROOT', role: 'DEVELOPER_ROOT', hierarchy: 'ALL', scope: ['NATIONAL','REGIONAL','DISTRICT','SCHOOL'] }); }
async function createSession(session) { await ensureInitialized(); await getPool().query('INSERT INTO server_sessions (id,token_hash,user_id,created_at,expires_at) VALUES (?,?,?,?,?)', [session.id, session.tokenHash, session.userId, iso(session.createdAt), iso(session.expiresAt)]); }
async function revokeSessionByHash(tokenHash) { if (!isConfigured()) return; await ensureInitialized(); await getPool().query('UPDATE server_sessions SET revoked_at = CURRENT_TIMESTAMP WHERE token_hash = ? AND revoked_at IS NULL', [tokenHash]); }
async function appendAudit(event) { await ensureInitialized(); await getPool().query('INSERT INTO audit_events (id,event_type,actor_user_id,occurred_at,correlation_id,ip,user_agent,metadata_json) VALUES (?,?,?,?,?,?,?,?)', [event.id || newId('audit'), event.action || event.eventType, event.userId || null, iso(event.at || new Date()), event.correlationId || null, event.ip || null, event.userAgent || null, json(event)]); }
async function hydrateAuthState(db) {
  if (!isConfigured()) return db;
  await ensureInitialized();
  const [users] = await getPool().query(`SELECT u.*, c.password_hash, c.access_code_hash, r.name AS role_name FROM users u JOIN credentials c ON c.user_id=u.id LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id`);
  db.users = users.map((row) => rowToUser(row, row));
  const [sessions] = await getPool().query('SELECT id,token_hash AS tokenHash,user_id AS userId,created_at AS createdAt,expires_at AS expiresAt,revoked_at AS revokedAt,csrf_token_hash AS csrfTokenHash FROM server_sessions WHERE revoked_at IS NULL AND expires_at > CURRENT_TIMESTAMP');
  db.sessions = sessions;
  return db;
}
async function findPaymentIntent(userId,idempotencyKey){await ensureInitialized();const [rows]=await getPool().query('SELECT * FROM payment_intents WHERE user_id=? AND idempotency_key=? LIMIT 1',[userId,idempotencyKey]);return rows[0]||null;}
async function createPaymentIntent(input){await ensureInitialized();const now=iso(new Date());const id=input.id||newId('payintent');await getPool().query('INSERT INTO payment_intents (id,reference,idempotency_key,user_id,school_id,plan_id,amount,currency,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[id,input.reference,input.idempotencyKey,input.userId,input.schoolId||null,input.planId,input.amount,input.currency,input.status||'initialized',now,now]);return (await domainRows('SELECT * FROM payment_intents WHERE id=?',[id]))[0];}
async function findPaymentIntentByReference(userId,reference){await ensureInitialized();const [rows]=await getPool().query('SELECT * FROM payment_intents WHERE user_id=? AND reference=? LIMIT 1',[userId,reference]);return rows[0]||null;}
async function findPaymentTransaction(reference){await ensureInitialized();const [rows]=await getPool().query('SELECT * FROM payment_transactions WHERE reference=? LIMIT 1',[reference]);return rows[0]||null;}
async function recordVerifiedPayment(input){await ensureInitialized();const conn=await getPool().getConnection();try{await conn.beginTransaction();const [dups]=await conn.query('SELECT id FROM payment_transactions WHERE reference=? OR (? IS NOT NULL AND provider_event_id=?) LIMIT 1',[input.reference,input.eventId||null,input.eventId||null]);if(dups.length){await conn.commit();return {duplicate:true,transaction:dups[0]};}const [intentRows]=await conn.query('SELECT * FROM payment_intents WHERE reference=? AND user_id=? FOR UPDATE',[input.reference,input.userId]);if(!intentRows.length)throw Object.assign(new Error('PAYMENT_NOT_FOUND'),{code:'PAYMENT_NOT_FOUND'});const intent=intentRows[0];const [subs]=await conn.query(`SELECT * FROM subscriptions WHERE user_id=? AND status='ACTIVE' ORDER BY expires_at DESC LIMIT 1 FOR UPDATE`,[input.userId]);const now=new Date();const start=subs.length&&new Date(subs[0].expires_at)>now?new Date(subs[0].expires_at):now;const expires=new Date(start.getTime()+input.durationDays*86400000);const txId=input.transactionId||newId('txn');await conn.query('INSERT INTO payment_transactions (id,reference,intent_id,user_id,school_id,plan_id,amount,currency,status,provider_event_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[txId,input.reference,intent.id,input.userId,input.schoolId||intent.school_id||null,input.planId,intent.amount,intent.currency,'success',input.eventId||null,iso(now)]);let subId;if(subs.length){subId=subs[0].id;await conn.query(`UPDATE subscriptions SET plan_id=?,status='ACTIVE',starts_at=?,expires_at=?,payment_reference=?,last_transaction_id=?,renewal_state=?,updated_at=? WHERE id=?`,[input.planId,iso(start),iso(expires),input.reference,txId,'RENEWED',iso(now),subId]);}else{subId=newId('sub');await conn.query('INSERT INTO subscriptions (id,user_id,school_id,plan_id,status,starts_at,expires_at,payment_reference,last_transaction_id,renewal_state,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',[subId,input.userId,input.schoolId||intent.school_id||null,input.planId,'ACTIVE',iso(start),iso(expires),input.reference,txId,'INITIAL',iso(now),iso(now)]);}if(input.eventId)await conn.query('INSERT INTO payment_events (id,event_id,reference,event_type,payload_json,received_at) VALUES (?,?,?,?,?,?)',[newId('payevent'),input.eventId,input.reference,input.eventType||'charge.success',json(input.payload||null),iso(now)]);await conn.query(`UPDATE payment_intents SET status='verified',updated_at=? WHERE id=?`,[iso(now),intent.id]);await conn.commit();return {duplicate:false,transaction:{id:txId,reference:input.reference,status:'success'},subscription:{id:subId}};}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
async function createPasswordReset(input){await ensureInitialized();await getPool().query('INSERT INTO password_reset_records (id,user_id,token_hash,created_at,expires_at,used_at) VALUES (?,?,?,?,?,NULL)',[input.id||newId('reset'),input.userId,input.tokenHash,iso(input.createdAt||new Date()),iso(input.expiresAt)]);}
async function findPasswordReset(tokenHash){await ensureInitialized();const [rows]=await getPool().query('SELECT * FROM password_reset_records WHERE token_hash=? AND used_at IS NULL AND expires_at>CURRENT_TIMESTAMP LIMIT 1',[tokenHash]);return rows[0]||null;}
async function consumePasswordReset(id){await ensureInitialized();const [result]=await getPool().query('UPDATE password_reset_records SET used_at=CURRENT_TIMESTAMP WHERE id=? AND used_at IS NULL AND expires_at>CURRENT_TIMESTAMP',[id]);return result.affectedRows===1;}
async function updateCredentialHashes(userId,passwordHash,accessCodeHash){await ensureInitialized();await getPool().query('UPDATE credentials SET password_hash=?,access_code_hash=?,updated_at=? WHERE user_id=?',[passwordHash,accessCodeHash||null,iso(new Date()),userId]);await getPool().query('UPDATE server_sessions SET revoked_at=CURRENT_TIMESTAMP WHERE user_id=? AND revoked_at IS NULL',[userId]);}
async function createFileRecord(input){await ensureInitialized();await getPool().query('INSERT INTO file_records (id,owner_user_id,school_id,storage_name,original_name,mime_type,size_bytes,category,associated_entity,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)',[input.id||newId('file'),input.ownerUserId,input.schoolId||null,input.storageName,input.originalName,input.mimeType,input.size,input.category,input.associatedEntity||null,iso(input.createdAt||new Date())]);return (await domainRows('SELECT * FROM file_records WHERE id=?',[input.id]))[0]||null;}
async function findFileRecord(id){await ensureInitialized();const [rows]=await getPool().query('SELECT * FROM file_records WHERE id=? LIMIT 1',[id]);return rows[0]||null;}
async function migrationCounts(){await ensureInitialized();const names=['payment_intents','payment_transactions','subscriptions','payment_events','password_reset_records','file_records'];const out={};for(const n of names){const [r]=await getPool().query('SELECT COUNT(*) count FROM '+n);out[n]=Number(r[0].count);}return out;}
async function importJson(jsonPath) {
  await ensureInitialized();
  const source = JSON.parse(fs.readFileSync(path.resolve(jsonPath), 'utf8'));
  for (const user of source.users || []) await upsertUser(user);
  for (const region of source.regions || []) await getPool().query('INSERT INTO regions (id,name) VALUES (?,?) ON DUPLICATE KEY UPDATE name=VALUES(name)', [region.id || newId('reg'), region.name]);
  return { users: (source.users || []).length, regions: (source.regions || []).length, imported: true };
}
async function resolveAuthorization(userId) {
  await ensureInitialized();
  const [users] = await getPool().query('SELECT id,status,active,development_fixture FROM users WHERE id=? LIMIT 1', [userId]);
  if (!users.length) return null;
  const [roles] = await getPool().query('SELECT r.name FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=?', [userId]);
  const [permissions] = await getPool().query('SELECT DISTINCT p.name FROM user_roles ur JOIN role_permissions rp ON rp.role_id=ur.role_id JOIN permissions p ON p.id=rp.permission_id WHERE ur.user_id=?', [userId]);
  const [memberships] = await getPool().query('SELECT tenant_id,scope_json,active FROM tenant_memberships WHERE user_id=?', [userId]);
  return { user: users[0], roles: roles.map((row) => row.name), permissions: permissions.map((row) => row.name), memberships: memberships.filter((row) => row.active).map((row) => ({ tenantId: row.tenant_id, scope: parseJson(row.scope_json, {}) })) };
}
async function domainRows(sql, params = []) { await ensureInitialized(); const [rows] = await getPool().query(sql, params); return rows; }
async function createSchool(input) {
  await ensureInitialized(); const conn = await getPool().getConnection(); const id = input.id || newId('school'); const now = iso(new Date());
  try { await conn.beginTransaction(); const [hierarchy] = await conn.query('SELECT d.id AS district_id,d.region_id,t.id AS tenant_id FROM districts d JOIN tenants t ON t.id=? AND t.active=TRUE WHERE d.id=? AND d.region_id=? LIMIT 1', [input.tenantId, input.districtId, input.regionId]); if (!hierarchy.length) throw new Error('INVALID_HIERARCHY'); await conn.query('INSERT INTO schools (id,school_code,name,ownership_type,tenant_id,district_id,address,contact_phone,contact_email,registration_metadata,active,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)', [id,input.schoolCode,input.name,input.ownershipType,input.tenantId,input.districtId,input.address||null,input.contactPhone||null,input.contactEmail||null,json(input.registrationMetadata||{}),true,now,now]); await conn.commit(); return (await conn.query('SELECT * FROM schools WHERE id=?',[id]))[0][0]; } catch (error) { await conn.rollback(); throw error; } finally { conn.release(); }
}
async function updateSchool(id, input) { await ensureInitialized(); const fields=[]; const values=[]; for (const [key,column] of Object.entries({schoolCode:'school_code',name:'name',ownershipType:'ownership_type',address:'address',contactPhone:'contact_phone',contactEmail:'contact_email',active:'active'})) if (input[key] !== undefined) { fields.push(`${column}=?`); values.push(input[key]); } if (!fields.length) return null; values.push(new Date(),id); await getPool().query(`UPDATE schools SET ${fields.join(',')},updated_at=? WHERE id=?`,values); const rows=await domainRows('SELECT * FROM schools WHERE id=?',[id]); return rows[0]||null; }
async function createStaff(input) { await ensureInitialized(); const conn=await getPool().getConnection(); const id=input.id||newId('staff'); const now=iso(new Date()); try { await conn.beginTransaction(); await conn.query('INSERT INTO staff (id,user_id,staff_identifier,full_name,phone,email,staff_type,status,tenant_id,region_id,district_id,school_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[id,input.userId||null,input.staffIdentifier,input.fullName,input.phone||null,input.email||null,input.staffType||'STAFF',input.status||'ACTIVE',input.tenantId,input.regionId||null,input.districtId||null,input.schoolId||null,now,now]); if(input.schoolId) await conn.query('INSERT INTO staff_school_assignments (staff_id,school_id,active,assigned_at) VALUES (?,?,1,?)',[id,input.schoolId,now]); if(input.userId&&input.role) { const [roles]=await conn.query('SELECT id FROM roles WHERE name=?',[input.role]); if(!roles.length) throw new Error('INVALID_ROLE'); await conn.query('INSERT INTO user_roles (user_id,role_id) VALUES (?,?)',[input.userId,roles[0].id]); } await conn.commit(); return (await conn.query('SELECT * FROM staff WHERE id=?',[id]))[0][0]; } catch(e){await conn.rollback();throw e;} finally{conn.release();} }
async function updateStaff(id,input){await ensureInitialized();const fields=[];const values=[];for(const [key,column] of Object.entries({fullName:'full_name',phone:'phone',email:'email',staffType:'staff_type',status:'status',schoolId:'school_id',districtId:'district_id',regionId:'region_id'}))if(input[key]!==undefined){fields.push(`${column}=?`);values.push(input[key]);}if(!fields.length)return null;values.push(new Date(),id);await getPool().query(`UPDATE staff SET ${fields.join(',')},updated_at=? WHERE id=?`,values);const rows=await domainRows('SELECT * FROM staff WHERE id=?',[id]);return rows[0]||null;}
async function createStudent(input){await ensureInitialized();const conn=await getPool().getConnection();const id=input.id||newId('student');const now=iso(new Date());try{await conn.beginTransaction();await conn.query('INSERT INTO students (id,admission_number,student_identifier,full_name,date_of_birth,gender,tenant_id,school_id,class_id,admission_date,special_needs,emergency_contact,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[id,input.admissionNumber,input.studentIdentifier,input.fullName,input.dateOfBirth||null,input.gender||null,input.tenantId,input.schoolId,input.classId||null,input.admissionDate||null,input.specialNeeds||null,input.emergencyContact||null,input.status||'ACTIVE',now,now]);if(input.parentUserId){const [parent]=await conn.query('SELECT u.id FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id WHERE u.id=? AND r.name=\'PARENT\' AND u.active=TRUE',[input.parentUserId]);if(!parent.length)throw new Error('INVALID_PARENT');await conn.query('INSERT INTO parent_student_relationships (parent_user_id,student_id,relationship_type,active,created_at) VALUES (?,?,?,1,?)',[input.parentUserId,id,input.relationshipType||'PARENT',now]);}await conn.commit();return (await conn.query('SELECT * FROM students WHERE id=?',[id]))[0][0];}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
async function updateStudent(id,input){await ensureInitialized();const fields=[];const values=[];for(const [key,column] of Object.entries({fullName:'full_name',dateOfBirth:'date_of_birth',gender:'gender',classId:'class_id',admissionDate:'admission_date',specialNeeds:'special_needs',emergencyContact:'emergency_contact',status:'status'}))if(input[key]!==undefined){fields.push(`${column}=?`);values.push(input[key]);}if(!fields.length)return null;values.push(new Date(),id);await getPool().query(`UPDATE students SET ${fields.join(',')},updated_at=? WHERE id=?`,values);const rows=await domainRows('SELECT * FROM students WHERE id=?',[id]);return rows[0]||null;}
async function createClass(input){await ensureInitialized();const id=input.id||newId('class');const now=iso(new Date());await getPool().query('INSERT INTO classes (id,name,school_id,tenant_id,academic_config_ref,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)',[id,input.name,input.schoolId,input.tenantId,input.academicConfigRef||null,input.status||'ACTIVE',now,now]);return (await domainRows('SELECT * FROM classes WHERE id=?',[id]))[0];}
async function updateClass(id,input){await ensureInitialized();const fields=[];const values=[];for(const [key,column] of Object.entries({name:'name',academicConfigRef:'academic_config_ref',status:'status'}))if(input[key]!==undefined){fields.push(`${column}=?`);values.push(input[key]);}if(!fields.length)return null;values.push(new Date(),id);await getPool().query(`UPDATE classes SET ${fields.join(',')},updated_at=? WHERE id=?`,values);return (await domainRows('SELECT * FROM classes WHERE id=?',[id]))[0]||null;}
async function assignStaffSchool(staffId,schoolId){await ensureInitialized();await getPool().query('INSERT INTO staff_school_assignments (staff_id,school_id,active,assigned_at) VALUES (?,?,1,?) ON DUPLICATE KEY UPDATE active=1',[staffId,schoolId,new Date()]);await getPool().query('UPDATE staff SET school_id=?,updated_at=? WHERE id=?',[schoolId,new Date(),staffId]);return true;}
async function assignTeacherClass(staffId,classId){await ensureInitialized();await getPool().query('INSERT INTO teacher_class_assignments (staff_id,class_id,active,assigned_at) VALUES (?,?,1,?) ON DUPLICATE KEY UPDATE active=1',[staffId,classId,new Date()]);return true;}
async function addParentStudent(parentUserId,studentId,relationshipType='PARENT'){await ensureInitialized();await getPool().query('INSERT INTO parent_student_relationships (parent_user_id,student_id,relationship_type,active,created_at) VALUES (?,?,?,1,?)',[parentUserId,studentId,relationshipType,new Date()]);return true;}

async function academicRows(sql, params = []) { return domainRows(sql, params); }
async function createAcademicConfig(input, actorId) { await ensureInitialized(); const id=input.id||newId('acadcfg'); const now=iso(new Date()); await getPool().query('INSERT INTO academic_configurations (id,tenant_id,school_id,academic_year,term,week,opening_date,closing_date,status,metadata_json,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',[id,input.tenantId,input.schoolId,input.academicYear,input.term,input.week||null,input.openingDate,input.closingDate,input.status||'DRAFT',json(input.metadata||null),actorId||null,now,now]); return (await academicRows('SELECT * FROM academic_configurations WHERE id=?',[id]))[0]; }
async function updateAcademicConfig(id,input) { await ensureInitialized(); const map={academicYear:'academic_year',term:'term',week:'week',openingDate:'opening_date',closingDate:'closing_date',status:'status',metadata:'metadata_json'}; const fields=[],values=[]; for(const [k,c] of Object.entries(map)) if(input[k]!==undefined){fields.push(c+'=?');values.push(k==='metadata'?json(input[k]):input[k]);} if(!fields.length)return (await academicRows('SELECT * FROM academic_configurations WHERE id=?',[id]))[0]||null; values.push(new Date(),id); await getPool().query('UPDATE academic_configurations SET '+fields.join(',')+',updated_at=? WHERE id=?',values); return (await academicRows('SELECT * FROM academic_configurations WHERE id=?',[id]))[0]||null; }
async function createSubject(input){await ensureInitialized();const id=input.id||newId('subject');const now=iso(new Date());await getPool().query('INSERT INTO subjects (id,tenant_id,school_id,code,name,status,metadata_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)',[id,input.tenantId,input.schoolId,input.code,input.name,input.status||'ACTIVE',json(input.metadata||null),now,now]);return (await academicRows('SELECT * FROM subjects WHERE id=?',[id]))[0];}
async function updateSubject(id,input){await ensureInitialized();const fields=[],values=[];for(const [k,c] of Object.entries({code:'code',name:'name',status:'status',metadata:'metadata_json'}))if(input[k]!==undefined){fields.push(c+'=?');values.push(k==='metadata'?json(input[k]):input[k]);}if(!fields.length)return (await academicRows('SELECT * FROM subjects WHERE id=?',[id]))[0]||null;values.push(new Date(),id);await getPool().query('UPDATE subjects SET '+fields.join(',')+',updated_at=? WHERE id=?',values);return (await academicRows('SELECT * FROM subjects WHERE id=?',[id]))[0]||null;}
async function createAttendance(input,actorId){await ensureInitialized();const conn=await getPool().getConnection();try{await conn.beginTransaction();const now=iso(new Date());const type=input.registerType||'STUDENT';const [existing]=await conn.query('SELECT id FROM attendance_registers WHERE class_id=? AND attendance_date=? AND register_type=? FOR UPDATE',[input.classId,input.attendanceDate,type]);const id=input.id||(existing[0]&&existing[0].id)||newId('attreg');if(existing.length){await conn.query('UPDATE attendance_registers SET academic_config_id=?,updated_at=? WHERE id=?',[input.academicConfigId||null,now,id]);}else{await conn.query('INSERT INTO attendance_registers (id,tenant_id,school_id,class_id,academic_config_id,attendance_date,register_type,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)',[id,input.tenantId,input.schoolId,input.classId,input.academicConfigId||null,input.attendanceDate,type,actorId||null,now,now]);}for(const rec of input.records||[])await conn.query('INSERT INTO student_attendance_records (id,register_id,student_id,status,note,recorded_by,recorded_at,updated_at) VALUES (?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE status=VALUES(status),note=VALUES(note),recorded_by=VALUES(recorded_by),updated_at=VALUES(updated_at)',[newId('att'),id,rec.studentId,rec.status,rec.note||null,actorId||null,now,now]);await conn.commit();return (await domainRows('SELECT * FROM attendance_registers WHERE id=?',[id]))[0];}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
async function updateAttendance(id,input,actorId){await ensureInitialized();const fields=[],values=[];if(input.status!==undefined){fields.push('status=?');values.push(input.status)}if(input.note!==undefined){fields.push('note=?');values.push(input.note)}if(!fields.length)return (await academicRows('SELECT * FROM student_attendance_records WHERE id=?',[id]))[0]||null;values.push(new Date(),id);await getPool().query('UPDATE student_attendance_records SET '+fields.join(',')+',updated_at=? WHERE id=?',values);return (await academicRows('SELECT * FROM student_attendance_records WHERE id=?',[id]))[0]||null;}
async function createExamination(input,actorId){await ensureInitialized();const conn=await getPool().getConnection();try{await conn.beginTransaction();const id=input.id||newId('exam');const now=iso(new Date());await conn.query('INSERT INTO examinations (id,tenant_id,school_id,class_id,academic_config_id,examination_type_id,name,status,publication_status,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',[id,input.tenantId,input.schoolId,input.classId,input.academicConfigId,input.examinationTypeId,input.name,input.status||'DRAFT','UNPUBLISHED',actorId||null,now,now]);for(const c of input.components||[])await conn.query('INSERT INTO examination_components (id,examination_id,subject_id,name,maximum_score,position_no) VALUES (?,?,?,?,?,?)',[newId('component'),id,c.subjectId,c.name,c.maximumScore,c.positionNo||1]);await conn.commit();return (await academicRows('SELECT * FROM examinations WHERE id=?',[id]))[0];}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
async function updateExamination(id,input){await ensureInitialized();const fields=[],values=[];for(const [k,c] of Object.entries({name:'name',status:'status'}))if(input[k]!==undefined){fields.push(c+'=?');values.push(input[k]);}if(!fields.length)return (await academicRows('SELECT * FROM examinations WHERE id=?',[id]))[0]||null;values.push(new Date(),id);await getPool().query('UPDATE examinations SET '+fields.join(',')+',updated_at=? WHERE id=?',values);return (await academicRows('SELECT * FROM examinations WHERE id=?',[id]))[0]||null;}
async function createScore(input,actorId){await ensureInitialized();const id=input.id||newId('score');const now=iso(new Date());await getPool().query('INSERT INTO scores (id,tenant_id,school_id,class_id,student_id,subject_id,examination_id,component_id,raw_score,maximum_score,status,entered_by,entered_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[id,input.tenantId,input.schoolId,input.classId,input.studentId,input.subjectId,input.examinationId,input.componentId,input.rawScore,input.maximumScore,input.status||'DRAFT',actorId||null,now,now]);return (await academicRows('SELECT * FROM scores WHERE id=?',[id]))[0];}
async function updateScore(id,input){await ensureInitialized();const fields=[],values=[];for(const [k,c] of Object.entries({rawScore:'raw_score',status:'status'}))if(input[k]!==undefined){fields.push(c+'=?');values.push(input[k]);}if(!fields.length)return (await academicRows('SELECT * FROM scores WHERE id=?',[id]))[0]||null;values.push(new Date(),id);await getPool().query('UPDATE scores SET '+fields.join(',')+',updated_at=? WHERE id=?',values);return (await academicRows('SELECT * FROM scores WHERE id=?',[id]))[0]||null;}
async function createBulkScores(input,actorId){await ensureInitialized();const conn=await getPool().getConnection();const accepted=[],rejected=[];try{await conn.beginTransaction();for(let i=0;i<(input.rows||[]).length;i++){const row=input.rows[i];try{const raw=Number(row.rawScore);if(!Number.isFinite(raw)||raw<0)throw Object.assign(new Error('Score must be between zero and maximum score'),{code:'DOMAIN_VALIDATION'});const [refs]=await conn.query('SELECT s.id AS student_id,s.class_id,s.school_id,s.tenant_id,c.id AS component_id,c.subject_id,c.maximum_score,e.id AS examination_id,e.class_id AS examination_class,e.school_id AS examination_school,e.tenant_id AS examination_tenant FROM students s JOIN examinations e ON e.id=? JOIN examination_components c ON c.id=? AND c.examination_id=e.id WHERE s.id=? AND s.tenant_id=? AND s.school_id=? AND s.class_id=? AND e.tenant_id=? AND e.school_id=? AND e.class_id=?',[row.examinationId,row.componentId,row.studentId,input.tenantId,input.schoolId,input.classId,input.tenantId,input.schoolId,input.classId]);if(!refs.length||String(refs[0].subject_id)!==String(row.subjectId))throw Object.assign(new Error('Student, examination, subject, and component must belong to the same class and school'),{code:'DOMAIN_VALIDATION'});const max=Number(refs[0].maximum_score);if(!Number.isFinite(max)||raw>max)throw Object.assign(new Error('Score must be between zero and maximum score'),{code:'DOMAIN_VALIDATION'});const id=row.id||newId('score');const now=iso(new Date());await conn.query('INSERT INTO scores (id,tenant_id,school_id,class_id,student_id,subject_id,examination_id,component_id,raw_score,maximum_score,status,entered_by,entered_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE raw_score=VALUES(raw_score),maximum_score=VALUES(maximum_score),status=VALUES(status),entered_by=VALUES(entered_by),updated_at=VALUES(updated_at)',[id,input.tenantId,input.schoolId,input.classId,row.studentId,row.subjectId,row.examinationId,row.componentId,raw,max,row.status||'DRAFT',actorId||null,now,now]);accepted.push({index:i,studentId:row.studentId,componentId:row.componentId});}catch(e){rejected.push({index:i,reason:e.message||'Score rejected'});}}if(rejected.length)throw Object.assign(new Error('One or more scores were rejected'),{code:'DOMAIN_VALIDATION',details:{accepted,rejected}});await conn.commit();const ids=(input.rows||[]).map(x=>x.studentId);return await academicRows('SELECT * FROM scores WHERE tenant_id=? AND school_id=? AND class_id=? AND student_id IN ('+ids.map(()=>'?').join(',')+')',[input.tenantId,input.schoolId,input.classId,...ids]);}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
async function createMockScoresBulk(input,actorId){await ensureInitialized();const conn=await getPool().getConnection();try{await conn.beginTransaction();const ids=[];for(const item of input.records||[]){const raw=Number(item.rawScore);const mockId=item.mockExaminationId||input.mockExaminationId;if(!mockId)throw Object.assign(new Error('Mock examination is required'),{code:'DOMAIN_VALIDATION'});if(!Number.isFinite(raw)||raw<0)throw Object.assign(new Error('Mock score must be between zero and maximum score'),{code:'DOMAIN_VALIDATION'});const [refs]=await conn.query('SELECT m.tenant_id,m.school_id,m.class_id,mc.id AS component_id,mc.maximum_score FROM mock_examinations m JOIN mock_components mc ON mc.id=? AND mc.mock_examination_id=m.id JOIN students s ON s.id=? AND s.tenant_id=m.tenant_id AND s.school_id=m.school_id AND s.class_id=m.class_id WHERE m.id=? AND m.tenant_id=? AND m.school_id=? AND m.class_id=?',[item.componentId,item.studentId,mockId,input.tenantId,input.schoolId,input.classId]);if(!refs.length)throw Object.assign(new Error('Mock student and component must belong to the same class and school'),{code:'DOMAIN_VALIDATION'});const max=Number(refs[0].maximum_score);if(raw>max)throw Object.assign(new Error('Mock score must be between zero and maximum score'),{code:'DOMAIN_VALIDATION'});const id=item.id||newId('mockscore');const now=iso(new Date());await conn.query('INSERT INTO mock_scores (id,mock_examination_id,component_id,student_id,raw_score,maximum_score,entered_by,entered_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE raw_score=VALUES(raw_score),maximum_score=VALUES(maximum_score),entered_by=VALUES(entered_by),updated_at=VALUES(updated_at)',[id,mockId,item.componentId,item.studentId,raw,max,actorId||null,now,now]);ids.push(id);}await conn.commit();return await academicRows('SELECT * FROM mock_scores WHERE id IN ('+ids.map(()=>'?').join(',')+') ORDER BY updated_at DESC',ids);}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
async function createMockScore(input,actorId){await ensureInitialized();const conn=await getPool().getConnection();try{await conn.beginTransaction();const raw=Number(input.rawScore);if(!Number.isFinite(raw)||raw<0)throw Object.assign(new Error('Mock score must be between zero and maximum score'),{code:'DOMAIN_VALIDATION'});const [refs]=await conn.query('SELECT m.tenant_id,m.school_id,m.class_id,mc.id AS component_id,mc.maximum_score FROM mock_examinations m JOIN mock_components mc ON mc.id=? AND mc.mock_examination_id=m.id JOIN students s ON s.id=? AND s.tenant_id=m.tenant_id AND s.school_id=m.school_id AND s.class_id=m.class_id WHERE m.id=? AND m.tenant_id=? AND m.school_id=? AND m.class_id=?',[input.componentId,input.studentId,input.mockExaminationId,input.tenantId,input.schoolId,input.classId]);if(!refs.length)throw Object.assign(new Error('Mock student and component must belong to the same class and school'),{code:'DOMAIN_VALIDATION'});const max=Number(refs[0].maximum_score);if(raw>max)throw Object.assign(new Error('Mock score must be between zero and maximum score'),{code:'DOMAIN_VALIDATION'});const id=input.id||newId('mockscore');const now=iso(new Date());await conn.query('INSERT INTO mock_scores (id,mock_examination_id,component_id,student_id,raw_score,maximum_score,entered_by,entered_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE raw_score=VALUES(raw_score),maximum_score=VALUES(maximum_score),entered_by=VALUES(entered_by),updated_at=VALUES(updated_at)',[id,input.mockExaminationId,input.componentId,input.studentId,raw,max,actorId||null,now,now]);await conn.commit();return (await academicRows('SELECT * FROM mock_scores WHERE mock_examination_id=? AND component_id=? AND student_id=?',[input.mockExaminationId,input.componentId,input.studentId]))[0];}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
async function calculateResult(input,actorId){await ensureInitialized();const conn=await getPool().getConnection();try{await conn.beginTransaction();const refs=await conn.query('SELECT s.id FROM students s JOIN examinations e ON e.id=? AND e.tenant_id=? AND e.school_id=? AND e.class_id=? JOIN academic_configurations ac ON ac.id=? AND ac.tenant_id=? AND ac.school_id=? WHERE s.id=? AND s.tenant_id=? AND s.school_id=? AND s.class_id=?',[input.examinationId,input.tenantId,input.schoolId,input.classId,input.academicConfigId,input.tenantId,input.schoolId,input.studentId,input.tenantId,input.schoolId,input.classId]);if(!refs[0].length)throw Object.assign(new Error('Student, examination, class, and academic configuration must belong to the same school and tenant'),{code:'DOMAIN_VALIDATION'});const scoreRows=await conn.query('SELECT raw_score,maximum_score,subject_id,component_id FROM scores WHERE tenant_id=? AND school_id=? AND class_id=? AND student_id=? AND examination_id=? ORDER BY subject_id,component_id',[input.tenantId,input.schoolId,input.classId,input.studentId,input.examinationId]);const rows=scoreRows[0],total=rows.reduce((n,x)=>n+Number(x.raw_score),0),max=rows.reduce((n,x)=>n+Number(x.maximum_score),0),payload={scoreCount:rows.length,total,max,percentage:max?Number((total/max*100).toFixed(2)):0,subjects:rows},existingRows=await conn.query('SELECT id FROM published_results WHERE tenant_id=? AND school_id=? AND class_id=? AND student_id=? AND academic_config_id=? AND examination_id=? ORDER BY version_no DESC LIMIT 1 FOR UPDATE',[input.tenantId,input.schoolId,input.classId,input.studentId,input.academicConfigId,input.examinationId]),now=iso(new Date());let resultId;if(existingRows[0].length){resultId=existingRows[0][0].id;await conn.query("UPDATE published_results SET result_json=?,publication_status='CALCULATED',published_by=NULL,published_at=NULL,updated_at=? WHERE id=?",[JSON.stringify(payload),now,resultId]);}else{resultId=input.id||newId('result');await conn.query('INSERT INTO published_results (id,tenant_id,school_id,class_id,student_id,academic_config_id,examination_id,version_no,result_json,publication_status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',[resultId,input.tenantId,input.schoolId,input.classId,input.studentId,input.academicConfigId,input.examinationId,1,JSON.stringify(payload),'CALCULATED',now,now]);}await conn.commit();return (await academicRows('SELECT * FROM published_results WHERE id=?',[resultId]))[0];}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
async function updateResultRemarks(resultId,remarks,actorId){await ensureInitialized();const conn=await getPool().getConnection();try{await conn.beginTransaction();const [rows]=await conn.query("SELECT * FROM published_results WHERE id=? AND publication_status='PUBLISHED' FOR UPDATE",[resultId]);if(!rows.length)throw Object.assign(new Error('Published result was not found'),{code:'DOMAIN_VALIDATION'});const current=parseJson(rows[0].result_json,{});const next=Object.assign({},current,{remarks});await conn.query('UPDATE published_results SET result_json=?,updated_at=? WHERE id=?',[JSON.stringify(next),iso(new Date()),resultId]);await conn.commit();return (await academicRows('SELECT * FROM published_results WHERE id=?',[resultId]))[0];}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
async function publishMockExamination(id,actorId){await ensureInitialized();await getPool().query("UPDATE mock_examinations SET publication_status='PUBLISHED',updated_at=? WHERE id=?",[new Date(),id]);return (await academicRows('SELECT * FROM mock_examinations WHERE id=?',[id]))[0]||null;}

async function saveTeacherAttendance(input,actorId,actorRole){await ensureInitialized();const conn=await getPool().getConnection();try{await conn.beginTransaction();const dates=[];for(const item of input.records||[]){const [staffRows]=await conn.query('SELECT id,status,user_id FROM staff WHERE tenant_id=? AND school_id=? AND (id=? OR staff_identifier=?) LIMIT 1',[input.tenantId,input.schoolId,item.staffId,item.staffId]);const staff=staffRows[0];if(!staff||String(staff.status).toUpperCase()!=='ACTIVE')throw Object.assign(new Error('Staff reference is invalid or inactive for this school'),{code:'DOMAIN_VALIDATION'});if(actorRole==='TEACHER'&&String(staff.user_id)!==String(actorId))throw Object.assign(new Error('Teachers may only update their own attendance'),{code:'AUTHORIZATION_DENIED'});const id=newId('teacher-att');const now=iso(new Date());await conn.query('INSERT INTO teacher_attendance_records (id,tenant_id,school_id,staff_id,attendance_date,status,sign_in,sign_out,note,recorded_by,recorded_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE status=COALESCE(VALUES(status),status),sign_in=COALESCE(VALUES(sign_in),sign_in),sign_out=COALESCE(VALUES(sign_out),sign_out),note=VALUES(note),recorded_by=VALUES(recorded_by),updated_at=VALUES(updated_at)',[id,input.tenantId,input.schoolId,staff.id,item.attendanceDate,item.status===undefined?null:String(item.status).toUpperCase(),item.signIn||null,item.signOut||null,item.note||null,actorId,now,now]);dates.push(item.attendanceDate);}await conn.commit();const marks=dates.map(()=>'?').join(',');return await academicRows('SELECT * FROM teacher_attendance_records WHERE tenant_id=? AND school_id=? AND attendance_date IN ('+marks+') ORDER BY attendance_date DESC',[input.tenantId,input.schoolId,...dates]);}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
async function createPromotionsBulk(input,actorId){await ensureInitialized();const conn=await getPool().getConnection();try{await conn.beginTransaction();const ids=[];for(const item of input.records||[]){if(item.sourceClassId===item.destinationClassId)throw Object.assign(new Error('Source and destination classes must differ'),{code:'DOMAIN_VALIDATION'});const [refs]=await conn.query('SELECT s.id FROM students s JOIN classes src ON src.id=? AND src.tenant_id=? AND src.school_id=? JOIN classes dst ON dst.id=? AND dst.tenant_id=? AND dst.school_id=? JOIN academic_configurations ac ON ac.id=? AND ac.tenant_id=? AND ac.school_id=? WHERE s.id=? AND s.tenant_id=? AND s.school_id=? AND s.class_id=?',[item.sourceClassId,input.tenantId,input.schoolId,item.destinationClassId,input.tenantId,input.schoolId,item.academicConfigId,input.tenantId,input.schoolId,item.studentId,input.tenantId,input.schoolId,item.sourceClassId]);if(!refs.length)throw Object.assign(new Error('Student, classes, and academic configuration must belong to the same school and tenant'),{code:'DOMAIN_VALIDATION'});const id=item.id||newId('promotion'),now=iso(new Date());await conn.query('INSERT INTO promotion_records (id,tenant_id,school_id,student_id,source_class_id,destination_class_id,academic_config_id,decision,status,decided_by,decided_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',[id,input.tenantId,input.schoolId,item.studentId,item.sourceClassId,item.destinationClassId,item.academicConfigId,item.decision||'PROMOTE',item.status||'DRAFT',actorId,item.status==='APPROVED'?now:null,now,now]);ids.push(id);}await conn.commit();return await academicRows('SELECT * FROM promotion_records WHERE id IN ('+ids.map(()=>'?').join(',')+') ORDER BY created_at DESC',ids);}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
async function createPromotion(input,actorId){await ensureInitialized();const id=input.id||newId('promotion');const now=iso(new Date());await getPool().query('INSERT INTO promotion_records (id,tenant_id,school_id,student_id,source_class_id,destination_class_id,academic_config_id,decision,status,decided_by,decided_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',[id,input.tenantId,input.schoolId,input.studentId,input.sourceClassId,input.destinationClassId,input.academicConfigId,input.decision||'PROMOTE',input.status||'DRAFT',actorId||null,input.status==='APPROVED'?now:null,now,now]);return (await academicRows('SELECT * FROM promotion_records WHERE id=?',[id]))[0];}
async function createMockExamination(input,actorId){await ensureInitialized();const conn=await getPool().getConnection();try{await conn.beginTransaction();const id=input.id||newId('mock');const now=iso(new Date());await conn.query('INSERT INTO mock_examinations (id,tenant_id,school_id,class_id,academic_config_id,label,format_code,status,publication_status,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',[id,input.tenantId,input.schoolId,input.classId,input.academicConfigId,input.label,input.formatCode||'B',input.status||'DRAFT','UNPUBLISHED',actorId||null,now,now]);for(const c of input.components||[])await conn.query('INSERT INTO mock_components (id,mock_examination_id,subject_id,name,maximum_score) VALUES (?,?,?,?,?)',[newId('mockcomp'),id,c.subjectId,c.name,c.maximumScore]);await conn.commit();return (await academicRows('SELECT * FROM mock_examinations WHERE id=?',[id]))[0];}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
async function createAcademicReport(input,actorId){await ensureInitialized();const id=input.id||newId('academic-report');const now=iso(new Date());await getPool().query('INSERT INTO academic_report_snapshots (id,tenant_id,school_id,class_id,report_type,filter_json,snapshot_json,created_by,created_at) VALUES (?,?,?,?,?,?,?,?,?)',[id,input.tenantId,input.schoolId||null,input.classId||null,input.reportType,json(input.filters||null),json(input.snapshot||{}),actorId||null,now]);return (await academicRows('SELECT * FROM academic_report_snapshots WHERE id=?',[id]))[0];}

async function tableCounts() { await ensureInitialized(); const out = {}; for (const table of ['users','credentials','roles','permissions','user_roles','tenants','tenant_memberships','regions','districts','schools','staff','students','classes','parent_student_relationships','staff_school_assignments','teacher_class_assignments','server_sessions','audit_events','payment_intents','payment_transactions','subscriptions','payment_events','password_reset_records','file_records','schema_migrations']) { const [rows] = await getPool().query(`SELECT COUNT(*) AS count FROM ${table}`); out[table] = Number(rows[0].count); } return out; }
async function close() { if (pool) { await pool.end(); pool = null; initialized = null; } }

module.exports = { DATABASE_URL, isConfigured, migrate, ensureInitialized, findUser, findUserById, upsertUser, provisionDevelopmentAccount, createSession, revokeSessionByHash, appendAudit, hydrateAuthState, resolveAuthorization, domainRows, createSchool, updateSchool, createStaff, updateStaff, createStudent, updateStudent, createClass, updateClass, assignStaffSchool, assignTeacherClass, addParentStudent, importJson, academicRows, createAcademicConfig, updateAcademicConfig, createSubject, updateSubject, createAttendance, updateAttendance, createExamination, updateExamination, createScore, updateScore, createBulkScores, createMockScore, createMockScoresBulk, updateResultRemarks, publishMockExamination, createPromotion, createPromotionsBulk, saveTeacherAttendance, calculateResult, createMockExamination, findPaymentIntent, createPaymentIntent, findPaymentIntentByReference, findPaymentTransaction, recordVerifiedPayment, createPasswordReset, findPasswordReset, consumePasswordReset, updateCredentialHashes, createFileRecord, findFileRecord, migrationCounts, tableCounts, close };
