CREATE TABLE IF NOT EXISTS schema_migrations (version INT PRIMARY KEY, name VARCHAR(160) NOT NULL, applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS users (id VARCHAR(80) PRIMARY KEY, email VARCHAR(254) NOT NULL UNIQUE, staff_id VARCHAR(120) NULL UNIQUE, status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE', active BOOLEAN NOT NULL DEFAULT TRUE, development_fixture BOOLEAN NOT NULL DEFAULT FALSE, hierarchy VARCHAR(80) NULL, scope_json JSON NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, revoked_at TIMESTAMP NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS credentials (id VARCHAR(80) PRIMARY KEY, user_id VARCHAR(80) NOT NULL, password_hash TEXT NOT NULL, access_code_hash TEXT NULL, status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY credentials_user_unique (user_id), CONSTRAINT credentials_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS roles (id VARCHAR(80) PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE, description VARCHAR(255) NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS permissions (id VARCHAR(100) PRIMARY KEY, name VARCHAR(120) NOT NULL UNIQUE, description VARCHAR(255) NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS role_permissions (role_id VARCHAR(80) NOT NULL, permission_id VARCHAR(100) NOT NULL, PRIMARY KEY (role_id, permission_id), CONSTRAINT role_permissions_role_fk FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE, CONSTRAINT role_permissions_permission_fk FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS user_roles (user_id VARCHAR(80) NOT NULL, role_id VARCHAR(80) NOT NULL, assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (user_id, role_id), CONSTRAINT user_roles_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT user_roles_role_fk FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS tenants (id VARCHAR(80) PRIMARY KEY, name VARCHAR(180) NOT NULL, tenant_type VARCHAR(40) NOT NULL, parent_id VARCHAR(80) NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, CONSTRAINT tenants_parent_fk FOREIGN KEY (parent_id) REFERENCES tenants(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS tenant_memberships (user_id VARCHAR(80) NOT NULL, tenant_id VARCHAR(80) NOT NULL, scope_json JSON NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (user_id, tenant_id), CONSTRAINT memberships_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT memberships_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS regions (id VARCHAR(80) PRIMARY KEY, name VARCHAR(180) NOT NULL UNIQUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS districts (id VARCHAR(80) PRIMARY KEY, region_id VARCHAR(80) NOT NULL, name VARCHAR(180) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY district_region_name (region_id, name), CONSTRAINT districts_region_fk FOREIGN KEY (region_id) REFERENCES regions(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS schools (id VARCHAR(80) PRIMARY KEY, school_code VARCHAR(120) NULL UNIQUE, tenant_id VARCHAR(80) NULL, district_id VARCHAR(80) NULL, name VARCHAR(255) NOT NULL, ownership_type VARCHAR(32) NOT NULL DEFAULT 'PRIVATE', first_term_free_used BOOLEAN NOT NULL DEFAULT FALSE, first_term_free_used_at TIMESTAMP NULL, sms_credits_balance INT NOT NULL DEFAULT 0, address VARCHAR(255) NULL, contact_phone VARCHAR(80) NULL, contact_email VARCHAR(254) NULL, registration_metadata JSON NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT schools_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL, CONSTRAINT schools_district_fk FOREIGN KEY (district_id) REFERENCES districts(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS staff (id VARCHAR(80) PRIMARY KEY, user_id VARCHAR(80) NULL, staff_identifier VARCHAR(120) NOT NULL UNIQUE, full_name VARCHAR(255) NOT NULL, phone VARCHAR(80) NULL, email VARCHAR(254) NULL, staff_type VARCHAR(80) NOT NULL DEFAULT 'STAFF', status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE', tenant_id VARCHAR(80) NOT NULL, region_id VARCHAR(80) NULL, district_id VARCHAR(80) NULL, school_id VARCHAR(80) NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY staff_user_unique (user_id), CONSTRAINT staff_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL, CONSTRAINT staff_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT, CONSTRAINT staff_region_fk FOREIGN KEY (region_id) REFERENCES regions(id) ON DELETE SET NULL, CONSTRAINT staff_district_fk FOREIGN KEY (district_id) REFERENCES districts(id) ON DELETE SET NULL, CONSTRAINT staff_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS students (id VARCHAR(80) PRIMARY KEY, admission_number VARCHAR(120) NOT NULL UNIQUE, student_identifier VARCHAR(120) NOT NULL UNIQUE, full_name VARCHAR(255) NOT NULL, date_of_birth DATE NULL, gender VARCHAR(40) NULL, tenant_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, class_id VARCHAR(80) NULL, admission_date DATE NULL, special_needs TEXT NULL, emergency_contact VARCHAR(255) NULL, status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, CONSTRAINT students_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT, CONSTRAINT students_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS student_status_history (id VARCHAR(80) PRIMARY KEY, student_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, from_status VARCHAR(32) NULL, to_status VARCHAR(32) NOT NULL, changed_at TIMESTAMP NOT NULL, changed_by VARCHAR(80) NULL, reason VARCHAR(160) NULL, created_at TIMESTAMP NOT NULL, KEY student_status_history_student (student_id,changed_at), KEY student_status_history_school (school_id,changed_at), CONSTRAINT student_status_history_student_fk FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE, CONSTRAINT student_status_history_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE, CONSTRAINT student_status_history_actor_fk FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS classes (id VARCHAR(80) PRIMARY KEY, name VARCHAR(160) NOT NULL, school_id VARCHAR(80) NOT NULL, tenant_id VARCHAR(80) NOT NULL, academic_config_ref VARCHAR(120) NULL, status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY class_school_name (school_id,name), CONSTRAINT classes_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE RESTRICT, CONSTRAINT classes_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS parent_student_relationships (parent_user_id VARCHAR(80) NOT NULL, student_id VARCHAR(80) NOT NULL, relationship_type VARCHAR(80) NOT NULL DEFAULT 'PARENT', active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL, PRIMARY KEY (parent_user_id,student_id), CONSTRAINT ps_parent_fk FOREIGN KEY (parent_user_id) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT ps_student_fk FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS staff_school_assignments (staff_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, assigned_at TIMESTAMP NOT NULL, PRIMARY KEY (staff_id,school_id), CONSTRAINT ssa_staff_fk FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE, CONSTRAINT ssa_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS teacher_class_assignments (staff_id VARCHAR(80) NOT NULL, class_id VARCHAR(80) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, assigned_at TIMESTAMP NOT NULL, PRIMARY KEY (staff_id,class_id), CONSTRAINT tca_staff_fk FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE, CONSTRAINT tca_class_fk FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS server_sessions (id VARCHAR(80) PRIMARY KEY, token_hash CHAR(64) NOT NULL UNIQUE, user_id VARCHAR(80) NOT NULL, created_at TIMESTAMP NOT NULL, expires_at TIMESTAMP NOT NULL, revoked_at TIMESTAMP NULL, csrf_token_hash CHAR(64) NULL, CONSTRAINT sessions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS audit_events (id VARCHAR(80) PRIMARY KEY, event_type VARCHAR(120) NOT NULL, actor_user_id VARCHAR(80) NULL, occurred_at TIMESTAMP NOT NULL, correlation_id VARCHAR(160) NULL, ip VARCHAR(80) NULL, user_agent VARCHAR(300) NULL, metadata_json JSON NULL, CONSTRAINT audit_actor_fk FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS payment_intents (id VARCHAR(80) PRIMARY KEY, reference VARCHAR(120) NOT NULL UNIQUE, idempotency_key VARCHAR(120) NOT NULL, user_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NULL, plan_id VARCHAR(80) NOT NULL, school_type VARCHAR(32) NULL, term_id VARCHAR(160) NULL, academic_year VARCHAR(32) NULL, term_number TINYINT NULL, term_start_date DATE NULL, term_end_date DATE NULL, government_term_reference VARCHAR(160) NULL, private_reopening_date DATE NULL, private_vacation_date DATE NULL, subscription_sequence INT NULL, duration_days INT NOT NULL DEFAULT 90, active_student_count INT NULL, price_per_student DECIMAL(12,2) NULL, subscription_amount DECIMAL(12,2) NULL, economic_value DECIMAL(12,2) NULL, amount DECIMAL(12,2) NOT NULL, currency VARCHAR(12) NOT NULL, payment_provider VARCHAR(40) NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY payment_intent_user_key (user_id,idempotency_key), KEY payment_intent_school (school_id), CONSTRAINT payment_intent_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT, CONSTRAINT payment_intent_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS payment_transactions (id VARCHAR(80) PRIMARY KEY, reference VARCHAR(120) NOT NULL UNIQUE, intent_id VARCHAR(80) NULL, user_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NULL, plan_id VARCHAR(80) NOT NULL, school_type VARCHAR(32) NULL, term_id VARCHAR(160) NULL, academic_year VARCHAR(32) NULL, term_number TINYINT NULL, term_start_date DATE NULL, term_end_date DATE NULL, government_term_reference VARCHAR(160) NULL, private_reopening_date DATE NULL, private_vacation_date DATE NULL, subscription_sequence INT NULL, active_student_count INT NULL, price_per_student DECIMAL(12,2) NULL, subscription_amount DECIMAL(12,2) NULL, economic_value DECIMAL(12,2) NULL, amount DECIMAL(12,2) NOT NULL, currency VARCHAR(12) NOT NULL, payment_provider VARCHAR(40) NULL, status VARCHAR(32) NOT NULL, provider_event_id VARCHAR(160) NULL UNIQUE, created_at TIMESTAMP NOT NULL, KEY payment_tx_user (user_id), KEY payment_tx_school_status (school_id,status), CONSTRAINT payment_tx_intent_fk FOREIGN KEY (intent_id) REFERENCES payment_intents(id) ON DELETE SET NULL, CONSTRAINT payment_tx_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT, CONSTRAINT payment_tx_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS subscriptions (id VARCHAR(80) PRIMARY KEY, user_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NULL, plan_id VARCHAR(80) NOT NULL, school_type VARCHAR(32) NULL, term_id VARCHAR(160) NULL, academic_year VARCHAR(32) NULL, term_number TINYINT NULL, government_term_reference VARCHAR(160) NULL, private_reopening_date DATE NULL, private_vacation_date DATE NULL, subscription_sequence INT NULL, status VARCHAR(32) NOT NULL, starts_at TIMESTAMP NOT NULL, expires_at TIMESTAMP NOT NULL, subscription_start_date DATE NULL, subscription_end_date DATE NULL, active_student_count_at_subscription INT NULL, price_per_student DECIMAL(12,2) NULL, subscription_amount DECIMAL(12,2) NULL, economic_value DECIMAL(12,2) NULL, currency VARCHAR(12) NULL, payment_status VARCHAR(32) NULL, payment_reference VARCHAR(120) NULL, payment_provider VARCHAR(40) NULL, last_transaction_id VARCHAR(80) NULL, renewal_state VARCHAR(32) NOT NULL DEFAULT 'INITIAL', created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, KEY subscription_user_status (user_id,status), KEY subscription_school_status (school_id,status), KEY subscription_expiry (expires_at), CONSTRAINT subscription_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT, CONSTRAINT subscription_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL, CONSTRAINT subscription_tx_fk FOREIGN KEY (last_transaction_id) REFERENCES payment_transactions(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS student_population_reconciliations (id VARCHAR(80) PRIMARY KEY, school_id VARCHAR(80) NOT NULL, academic_year VARCHAR(32) NOT NULL, term_number TINYINT NOT NULL, subscription_id VARCHAR(80) NOT NULL, subscription_timestamp TIMESTAMP NOT NULL, subscription_population INT NOT NULL, current_active_population INT NOT NULL, newly_admitted_population INT NOT NULL DEFAULT 0, withdrawn_population INT NOT NULL DEFAULT 0, transferred_population INT NOT NULL DEFAULT 0, stopped_population INT NOT NULL DEFAULT 0, inactive_population INT NOT NULL DEFAULT 0, net_active_difference INT NOT NULL, reconciliation_timestamp TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, KEY reconciliation_subscription (subscription_id,reconciliation_timestamp), KEY reconciliation_school_term (school_id,academic_year,term_number), CONSTRAINT reconciliation_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE, CONSTRAINT reconciliation_subscription_fk FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS subscription_carry_forward_records (id VARCHAR(80) PRIMARY KEY, school_id VARCHAR(80) NOT NULL, tenant_id VARCHAR(80) NULL, previous_subscription_id VARCHAR(80) NOT NULL, previous_baseline_population INT NOT NULL, previous_end_population INT NOT NULL, verified_carry_forward INT NOT NULL, next_subscription_id VARCHAR(80) NULL, next_subscription_population INT NULL, carry_forward_status VARCHAR(32) NOT NULL DEFAULT 'CALCULATED', calculation_timestamp TIMESTAMP NOT NULL, created_by VARCHAR(80) NULL, created_at TIMESTAMP NOT NULL, UNIQUE KEY carry_forward_previous_unique (previous_subscription_id), KEY carry_forward_school (school_id,calculation_timestamp), CONSTRAINT carry_forward_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE, CONSTRAINT carry_forward_previous_fk FOREIGN KEY (previous_subscription_id) REFERENCES subscriptions(id) ON DELETE CASCADE, CONSTRAINT carry_forward_next_fk FOREIGN KEY (next_subscription_id) REFERENCES subscriptions(id) ON DELETE SET NULL, CONSTRAINT carry_forward_creator_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS subscription_population_checkpoints (id VARCHAR(80) PRIMARY KEY, school_id VARCHAR(80) NOT NULL, tenant_id VARCHAR(80) NULL, subscription_id VARCHAR(80) NOT NULL, academic_year VARCHAR(32) NOT NULL, term_number TINYINT NOT NULL, checkpoint_type VARCHAR(24) NOT NULL, examination_id VARCHAR(80) NULL, report_type VARCHAR(80) NULL, checkpoint_timestamp TIMESTAMP NOT NULL, subscription_population INT NOT NULL, current_active_population INT NOT NULL, newly_admitted_population INT NOT NULL DEFAULT 0, withdrawn_population INT NOT NULL DEFAULT 0, transferred_population INT NOT NULL DEFAULT 0, stopped_population INT NOT NULL DEFAULT 0, inactive_population INT NOT NULL DEFAULT 0, examination_population INT NOT NULL DEFAULT 0, report_card_population INT NOT NULL DEFAULT 0, net_additional_students INT NOT NULL DEFAULT 0, carry_forward_students INT NOT NULL DEFAULT 0, active_without_report_cards INT NOT NULL DEFAULT 0, report_cards_for_inactive_students INT NOT NULL DEFAULT 0, report_cards_outside_school_tenant INT NOT NULL DEFAULT 0, population_discrepancy BOOLEAN NOT NULL DEFAULT FALSE, class_rows_json JSON NOT NULL, flags_json JSON NULL, created_by VARCHAR(80) NULL, created_at TIMESTAMP NOT NULL, UNIQUE KEY subscription_checkpoint_identity (subscription_id,checkpoint_type,checkpoint_timestamp), KEY checkpoint_school_term (school_id,academic_year,term_number,checkpoint_type), CONSTRAINT checkpoint_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE, CONSTRAINT checkpoint_subscription_fk FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE CASCADE, CONSTRAINT checkpoint_creator_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS payment_events (id VARCHAR(80) PRIMARY KEY, event_id VARCHAR(160) NOT NULL UNIQUE, reference VARCHAR(120) NOT NULL, event_type VARCHAR(80) NOT NULL, payload_json JSON NULL, received_at TIMESTAMP NOT NULL, KEY payment_event_reference (reference), CONSTRAINT payment_event_tx_fk FOREIGN KEY (reference) REFERENCES payment_transactions(reference) ON DELETE RESTRICT) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS password_reset_records (id VARCHAR(80) PRIMARY KEY, user_id VARCHAR(80) NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE, created_at TIMESTAMP NOT NULL, expires_at TIMESTAMP NOT NULL, used_at TIMESTAMP NULL, KEY reset_user_expiry (user_id,expires_at), CONSTRAINT reset_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS file_records (id VARCHAR(80) PRIMARY KEY, owner_user_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NULL, storage_name VARCHAR(255) NOT NULL UNIQUE, original_name VARCHAR(255) NOT NULL, mime_type VARCHAR(120) NOT NULL, size_bytes BIGINT NOT NULL, category VARCHAR(80) NOT NULL, associated_entity VARCHAR(160) NULL, created_at TIMESTAMP NOT NULL, KEY file_owner (owner_user_id), KEY file_school (school_id), CONSTRAINT file_owner_fk FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE RESTRICT, CONSTRAINT file_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS school_fees (id VARCHAR(80) PRIMARY KEY, tenant_id VARCHAR(80) NULL, school_id VARCHAR(80) NULL, name VARCHAR(180) NOT NULL, category VARCHAR(100) NOT NULL, amount DECIMAL(12,2) NOT NULL, due_date DATE NULL, term VARCHAR(40) NULL, academic_year VARCHAR(20) NULL, scope VARCHAR(30) NOT NULL DEFAULT 'school', scope_class VARCHAR(120) NULL, scope_student VARCHAR(120) NULL, publication_status VARCHAR(20) NOT NULL DEFAULT 'UNPUBLISHED', published_by VARCHAR(80) NULL, published_at TIMESTAMP NULL, created_by VARCHAR(80) NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, KEY fee_school_publication (school_id,publication_status), CONSTRAINT fee_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS school_fee_payments (id VARCHAR(80) PRIMARY KEY, fee_id VARCHAR(80) NULL, tenant_id VARCHAR(80) NULL, school_id VARCHAR(80) NULL, student_id VARCHAR(80) NOT NULL, receipt_no VARCHAR(120) NOT NULL UNIQUE, amount DECIMAL(12,2) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'CONFIRMED', paid_at TIMESTAMP NOT NULL, created_by VARCHAR(80) NULL, KEY fee_payment_student (student_id), CONSTRAINT fee_payment_fee_fk FOREIGN KEY (fee_id) REFERENCES school_fees(id) ON DELETE SET NULL, CONSTRAINT fee_payment_school_fk FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS hostels (id VARCHAR(80) PRIMARY KEY, tenant_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, name VARCHAR(180) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE', created_by VARCHAR(80), created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY hostel_school_name (school_id,name));
CREATE TABLE IF NOT EXISTS hostel_blocks (id VARCHAR(80) PRIMARY KEY, hostel_id VARCHAR(80) NOT NULL, name VARCHAR(120) NOT NULL, floors INT NOT NULL DEFAULT 1, status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY hostel_block_name (hostel_id,name));
CREATE TABLE IF NOT EXISTS hostel_rooms (id VARCHAR(80) PRIMARY KEY, block_id VARCHAR(80) NOT NULL, name VARCHAR(120) NOT NULL, capacity INT NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE', created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY hostel_room_name (block_id,name));
CREATE TABLE IF NOT EXISTS hostel_beds (id VARCHAR(80) PRIMARY KEY, room_id VARCHAR(80) NOT NULL, name VARCHAR(120) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'AVAILABLE', created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, UNIQUE KEY hostel_bed_name (room_id,name));
CREATE TABLE IF NOT EXISTS hostel_assignments (id VARCHAR(80) PRIMARY KEY, tenant_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, student_id VARCHAR(80) NOT NULL, hostel_id VARCHAR(80) NOT NULL, block_id VARCHAR(80), room_id VARCHAR(80), bed_id VARCHAR(80), assigned_at TIMESTAMP NOT NULL, vacated_at TIMESTAMP NULL, status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE', assigned_by VARCHAR(80), reason VARCHAR(255), KEY hostel_assignment_student (student_id,status), KEY hostel_assignment_school (school_id,status));
CREATE TABLE IF NOT EXISTS hostel_roll_calls (id VARCHAR(80) PRIMARY KEY, tenant_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, student_id VARCHAR(80) NOT NULL, session_name VARCHAR(80) NOT NULL, attendance_date DATE NOT NULL, status VARCHAR(20) NOT NULL, recorded_by VARCHAR(80), recorded_at TIMESTAMP NOT NULL, source VARCHAR(30) NOT NULL DEFAULT 'ONLINE', UNIQUE KEY hostel_rollcall_unique (school_id,student_id,session_name,attendance_date));
CREATE TABLE IF NOT EXISTS hostel_audit_events (id VARCHAR(80) PRIMARY KEY, tenant_id VARCHAR(80) NOT NULL, school_id VARCHAR(80) NOT NULL, action VARCHAR(80) NOT NULL, entity_type VARCHAR(50) NOT NULL, entity_id VARCHAR(80), actor_id VARCHAR(80), payload_json JSON, created_at TIMESTAMP NOT NULL);

CREATE TABLE IF NOT EXISTS transport_vehicles (id VARCHAR(80) PRIMARY KEY,tenant_id VARCHAR(80) NOT NULL,school_id VARCHAR(80) NOT NULL,registration_no VARCHAR(120) NOT NULL,name VARCHAR(180) NOT NULL,capacity INT NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',created_by VARCHAR(80),created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL,UNIQUE KEY transport_vehicle_reg (school_id,registration_no)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS transport_routes (id VARCHAR(80) PRIMARY KEY,tenant_id VARCHAR(80) NOT NULL,school_id VARCHAR(80) NOT NULL,name VARCHAR(180) NOT NULL,description TEXT,route_type VARCHAR(30) NOT NULL DEFAULT 'BOTH',status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',created_by VARCHAR(80),created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL,UNIQUE KEY transport_route_name (school_id,name)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS transport_stops (id VARCHAR(80) PRIMARY KEY,route_id VARCHAR(80) NOT NULL,name VARCHAR(180) NOT NULL,stop_order INT NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,UNIQUE KEY transport_stop_order (route_id,stop_order)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS transport_staff_assignments (id VARCHAR(80) PRIMARY KEY,tenant_id VARCHAR(80) NOT NULL,school_id VARCHAR(80) NOT NULL,vehicle_id VARCHAR(80) NOT NULL,staff_id VARCHAR(80) NOT NULL,staff_role VARCHAR(40) NOT NULL,effective_from DATE NOT NULL,effective_to DATE NULL,status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',created_by VARCHAR(80),created_at TIMESTAMP NOT NULL,KEY transport_staff_active (vehicle_id,status)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS transport_student_assignments (id VARCHAR(80) PRIMARY KEY,tenant_id VARCHAR(80) NOT NULL,school_id VARCHAR(80) NOT NULL,student_id VARCHAR(80) NOT NULL,route_id VARCHAR(80) NOT NULL,stop_id VARCHAR(80),vehicle_id VARCHAR(80),effective_from DATE NOT NULL,effective_to DATE NULL,status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',created_by VARCHAR(80),created_at TIMESTAMP NOT NULL,KEY transport_student_active (student_id,status),UNIQUE KEY transport_student_one_active (student_id,status)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS transport_events (id VARCHAR(80) PRIMARY KEY,tenant_id VARCHAR(80) NOT NULL,school_id VARCHAR(80) NOT NULL,student_id VARCHAR(80) NOT NULL,route_id VARCHAR(80),vehicle_id VARCHAR(80),event_date DATE NOT NULL,event_time TIMESTAMP NOT NULL,event_status VARCHAR(40) NOT NULL,source VARCHAR(30) NOT NULL DEFAULT 'MANUAL',recorded_by VARCHAR(80),created_at TIMESTAMP NOT NULL,UNIQUE KEY transport_event_unique (student_id,event_date,event_status)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS transport_locations (id VARCHAR(80) PRIMARY KEY,tenant_id VARCHAR(80) NOT NULL,school_id VARCHAR(80) NOT NULL,vehicle_id VARCHAR(80) NOT NULL,latitude DECIMAL(10,7) NOT NULL,longitude DECIMAL(10,7) NOT NULL,recorded_at TIMESTAMP NOT NULL,source VARCHAR(30) NOT NULL DEFAULT 'SIMULATION',recorded_by VARCHAR(80),KEY transport_location_latest (vehicle_id,recorded_at)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS transport_audit_events (id VARCHAR(80) PRIMARY KEY,tenant_id VARCHAR(80) NOT NULL,school_id VARCHAR(80) NOT NULL,action VARCHAR(80) NOT NULL,entity_type VARCHAR(50) NOT NULL,entity_id VARCHAR(80),actor_id VARCHAR(80),payload_json JSON,created_at TIMESTAMP NOT NULL) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS pending_admission_applications (id VARCHAR(80) PRIMARY KEY,application_reference VARCHAR(40) NOT NULL UNIQUE,admission_type VARCHAR(20) NOT NULL,tenant_id VARCHAR(80) NULL,region_id VARCHAR(80) NOT NULL,district_id VARCHAR(80) NOT NULL,school_id VARCHAR(80) NOT NULL,level VARCHAR(80) NOT NULL,class_id VARCHAR(80) NOT NULL,applicant_json JSON NOT NULL,guardian_json JSON NOT NULL,documents_json JSON NULL,status VARCHAR(32) NOT NULL DEFAULT 'PENDING_REVIEW',submitted_at TIMESTAMP NOT NULL,created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL,UNIQUE KEY pending_duplicate (school_id,admission_type,applicant_hash,status),applicant_hash CHAR(64) NOT NULL,KEY pending_school_status (school_id,status)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS admission_review_history (id VARCHAR(80) PRIMARY KEY,application_id VARCHAR(80) NOT NULL,school_id VARCHAR(80) NOT NULL,actor_user_id VARCHAR(80) NULL,action VARCHAR(80) NOT NULL,from_status VARCHAR(32) NULL,to_status VARCHAR(32) NULL,reason TEXT NULL,created_at TIMESTAMP NOT NULL,KEY arh_application (application_id,created_at));

CREATE TABLE IF NOT EXISTS communication_campaigns (id VARCHAR(80) PRIMARY KEY,tenant_id VARCHAR(80) NULL,name VARCHAR(180) NULL,channel VARCHAR(20) NOT NULL,subject VARCHAR(255) NULL,message TEXT NOT NULL,audience_json JSON NOT NULL,recipient_count INT NOT NULL DEFAULT 0,status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',created_at TIMESTAMP NOT NULL);

CREATE TABLE IF NOT EXISTS chat_conversations (id VARCHAR(80) PRIMARY KEY,school_id VARCHAR(80) NOT NULL,tenant_id VARCHAR(80) NULL,participant_a VARCHAR(80) NOT NULL,participant_b VARCHAR(80) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',created_at TIMESTAMP NOT NULL,last_message_at TIMESTAMP NULL);
CREATE TABLE IF NOT EXISTS chat_messages (id VARCHAR(80) PRIMARY KEY,conversation_id VARCHAR(80) NOT NULL,sender_id VARCHAR(80) NOT NULL,recipient_id VARCHAR(80) NOT NULL,body VARCHAR(4000) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'SENT',sent_at TIMESTAMP NOT NULL,read_at TIMESTAMP NULL,client_nonce VARCHAR(120) NOT NULL);

CREATE TABLE IF NOT EXISTS organization_branding (scope_type VARCHAR(30) NOT NULL,scope_id VARCHAR(80) NOT NULL,tenant_id VARCHAR(80) NULL,display_name VARCHAR(255) NULL,logo_url VARCHAR(1000) NULL,primary_color VARCHAR(20) NULL,accent_color VARCHAR(20) NULL,updated_by VARCHAR(80) NULL,updated_at TIMESTAMP NOT NULL,PRIMARY KEY(scope_type,scope_id));
